"""Card event types — unified event abstraction for card state management.

This package re-exports all public symbols for backwards compatibility.
Import pattern: ``from src.card.events import CardEvent, CardEventType``
"""

from src.card.events.acp_adapter import card_event_from_acp
from src.card.events.factories import VALIDATE_PAYLOAD, CardEvent
from src.card.events.payloads import (
    BlockedPayload,
    CompletedPayload,
    CriteriaUpdatedPayload,
    CycleDonePayload,
    CycleStartedPayload,
    FailedPayload,
    PhaseDonePayload,
    PhaseStartedPayload,
    PlanUpdatedPayload,
    ProgressPayload,
    ReasoningBlockPayload,
    ReviewResultUpdatedPayload,
    ReviewRetryPayload,
    SpecPlanUpdatedPayload,
    SpecTasksUpdatedPayload,
    TextBlockPayload,
    ToolDeltaPayload,
    ToolDonePayload,
    ToolFailedPayload,
    ToolModelChangedPayload,
    ToolStartedPayload,
    WarningPayload,
    WorkflowAgentDonePayload,
    WorkflowAgentFailedPayload,
    WorkflowAgentStartedPayload,
    WorkflowConfirmPayload,
    WorkflowLogPayload,
    WorkflowPhasePayload,
    WorkflowProgressPayload,
    WorktreeCleanupPayload,
    WorktreeConfirmPayload,
    WorktreeMergePayload,
    WorktreeProgressPayload,
    WorktreeToolSelectPayload,
    WorktreeUnitPayload,
)
from src.card.events.types import CardEventType
from src.card.events.workflow import (
    workflow_agent_done,
    workflow_agent_failed,
    workflow_agent_started,
    workflow_confirm,
    workflow_log,
    workflow_phase,
    workflow_progress,
)
from src.card.events.worktree import (
    worktree_cleanup,
    worktree_completed_no_change,
    worktree_confirm,
    worktree_merge,
    worktree_progress,
    worktree_tool_select,
)

__all__ = [
    "CardEvent",
    "CardEventType",
    "card_event_from_acp",
    "VALIDATE_PAYLOAD",
    "worktree_cleanup",
    "worktree_completed_no_change",
    "worktree_confirm",
    "worktree_merge",
    "worktree_progress",
    "worktree_tool_select",
    # Workflow factories
    "workflow_agent_done",
    "workflow_agent_failed",
    "workflow_agent_started",
    "workflow_confirm",
    "workflow_log",
    "workflow_phase",
    "workflow_progress",
    # Payloads
    "BlockedPayload",
    "CompletedPayload",
    "CriteriaUpdatedPayload",
    "CycleDonePayload",
    "CycleStartedPayload",
    "FailedPayload",
    "PhaseDonePayload",
    "PhaseStartedPayload",
    "PlanUpdatedPayload",
    "ProgressPayload",
    "ReasoningBlockPayload",
    "ReviewResultUpdatedPayload",
    "ReviewRetryPayload",
    "SpecPlanUpdatedPayload",
    "SpecTasksUpdatedPayload",
    "TextBlockPayload",
    "ToolDeltaPayload",
    "ToolDonePayload",
    "ToolFailedPayload",
    "ToolModelChangedPayload",
    "ToolStartedPayload",
    "WarningPayload",
    "WorktreeCleanupPayload",
    "WorktreeConfirmPayload",
    "WorktreeMergePayload",
    "WorktreeProgressPayload",
    "WorktreeToolSelectPayload",
    "WorktreeUnitPayload",
    "WorkflowConfirmPayload",
    "WorkflowAgentDonePayload",
    "WorkflowAgentFailedPayload",
    "WorkflowAgentStartedPayload",
    "WorkflowLogPayload",
    "WorkflowPhasePayload",
    "WorkflowProgressPayload",
]
