"""Immutable autonomous-domain aggregates and guarded transitions."""

from .control import (
    BudgetEntry,
    BudgetEntryState,
    BudgetLedger,
    GoalActivationAuthorization,
    Principal,
)
from .effects import (
    UNRESOLVED_EFFECT_STATES,
    CapabilityDescriptor,
    Effect,
    EffectDisposition,
    Evidence,
    ResourceQuarantine,
)
from .employees import BotPrincipal, EmployeeDefinition, WorkerRuntime
from .enums import (
    AttemptState,
    AutonomyMode,
    EffectDispositionType,
    EffectEvent,
    EffectState,
    EmployeeIdOrigin,
    EmployeeState,
    GoalState,
    GoalType,
    MisfirePolicy,
    OracleType,
    OverlapPolicy,
    PlanEvent,
    PlanState,
    RiskLevel,
    RunEvent,
    RunState,
    StepEvent,
    StepState,
    TurnOutputType,
    VerificationResult,
    WorkerType,
)
from .goals import (
    EpochSet,
    GoalCriterion,
    GoalDefinition,
    GoalSpec,
    Run,
    ScheduleCursor,
    TriggerSubscription,
)
from .ids import canonical_hash, freeze, new_id, thaw
from .plans import Attempt, GoalCriteriaCoverage, Plan, PlanStep
from .reporting import DecisionRequest, ProgressSnapshot, Report
from .state_machine import (
    CriterionMutationError,
    RunTransitionContext,
    TransitionRecord,
    TransitionRejected,
    assert_replan_criteria_compatible,
    transition_effect,
    transition_plan,
    transition_run,
    transition_step,
)

__all__ = [
    "Attempt",
    "AttemptState",
    "AutonomyMode",
    "BotPrincipal",
    "BudgetEntry",
    "BudgetEntryState",
    "BudgetLedger",
    "CapabilityDescriptor",
    "CriterionMutationError",
    "DecisionRequest",
    "Effect",
    "EffectDisposition",
    "EffectDispositionType",
    "EffectEvent",
    "EffectState",
    "EmployeeDefinition",
    "EmployeeIdOrigin",
    "EmployeeState",
    "EpochSet",
    "Evidence",
    "GoalActivationAuthorization",
    "GoalCriteriaCoverage",
    "GoalCriterion",
    "GoalDefinition",
    "GoalSpec",
    "GoalState",
    "GoalType",
    "MisfirePolicy",
    "OracleType",
    "OverlapPolicy",
    "Plan",
    "PlanEvent",
    "PlanState",
    "PlanStep",
    "Principal",
    "ProgressSnapshot",
    "Report",
    "ResourceQuarantine",
    "RiskLevel",
    "Run",
    "RunEvent",
    "RunState",
    "RunTransitionContext",
    "ScheduleCursor",
    "StepEvent",
    "StepState",
    "TransitionRecord",
    "TransitionRejected",
    "TriggerSubscription",
    "TurnOutputType",
    "UNRESOLVED_EFFECT_STATES",
    "VerificationResult",
    "WorkerRuntime",
    "WorkerType",
    "assert_replan_criteria_compatible",
    "canonical_hash",
    "freeze",
    "new_id",
    "thaw",
    "transition_effect",
    "transition_plan",
    "transition_run",
    "transition_step",
]
