"""Lock-related UI text constants.

Merged into the main ``UI_TEXT`` dict at import time in ``ui_text.py``.
"""

LOCK_UI_TEXT: dict[str, str] = {
    # ── Help Section ──
    "system_help_section_lock": "🔒 群锁定 · Bot 管理员专属",
    "system_help_section_lock_nonadmin": "🔒 群锁定",
    # ── Lock Interception ──
    "chat_locked_title": "🔒 群已锁定",
    "chat_unlocked_title": "🔓 群已解锁",
    "chat_locked_fallback": "🔒 群已锁定，请联系 Bot 管理员，发送 /status 查看详情",
    "chat_locked_throttled_reply": "群已被 {name} 锁定，非 Bot 管理员暂不可操作。发送 /status 查看详情",
    "chat_locked_throttled_reply_md": "群已被 {name} 锁定，非 Bot 管理员暂不可操作。\n发送 `/status` 查看详情",
    # ── Lock Duration Formatting ──
    "lock_duration_just_now": "刚刚",
    "lock_duration_seconds": "{n} 秒前",
    "lock_duration_minutes": "{n} 分钟前",
    "lock_duration_hours": "{h} 小时 {m} 分钟前",
    "lock_duration_days": "{d} 天 {h} 小时前",
    # ── Lock Held Duration (format_lock_duration) ──
    "lock_held_seconds": "已锁定 {n} 秒",
    "lock_held_minutes": "已锁定 {n} 分钟",
    "lock_held_hours_minutes": "已锁定 {h} 小时 {m} 分钟",
    "lock_held_hours": "已锁定 {h} 小时",
    # ── Repo Lock Card ──
    "repo_lock_card_header": "🔒 仓库锁定",
    "repo_lock_title": "**🔒 仓库锁定中**",
    "repo_lock_occupied": "仓库 `{repo_name}` 正被另一个群会话占用。",
    "repo_lock_duration_line": "锁定时间: {duration}",
    "repo_lock_hint_active": "💡 对方正在操作中（最近 {last_active_ago} 有操作），若对方 {timeout_min} 分钟内无新操作，系统将自动释放。",
    "repo_lock_hint_idle_countdown": "💡 对方暂无新操作（约 {idle_min} 分钟），系统将在 {remaining_min} 分钟后自动释放。",
    "repo_lock_hint_idle_imminent": "💡 对方暂无新操作（约 {idle_min} 分钟），锁即将自动释放。",
    "repo_lock_hint_idle_default": "💡 若对方 {timeout_min} 分钟内无操作，系统将自动释放。",
    "repo_lock_p2p_hint_link": "你可以[去私聊操作](lark://applink/client/bot/open?appId={app_id})该仓库（私聊不受仓库锁限制）。",
    "repo_lock_p2p_fallback_note": "若链接无法打开，请在飞书客户端中搜索本 Bot 进入私聊。",
    "repo_lock_p2p_hint_plain": "你可以在私聊中使用机器人操作该仓库（私聊不受仓库锁限制）。",
    "repo_lock_retry_hint": "稍后重新发送相同命令即可重试。可通过 `/status` 查看锁状态。",
    "repo_lock_concept_note": "此仓库锁由系统自动管理，与群锁定（/lock）无关。",
    "repo_lock_same_sender_hint": "💡 你在另一个群中持有该仓库锁。完成后锁会自动释放，或前往该群操作。\n",
    "repo_lock_cmd_too_long": "\n💡 命令较长，请手动重新发送。",
    "repo_lock_btn_retry": "🔄 重试",
    "repo_lock_btn_retry_nth": "🔄 重试 (第{n}次)",  # deprecated: retry count no longer shown to users
    "repo_lock_retry_still_occupied": "仓库仍被占用，已为你再次检查。{countdown_hint}",
    "repo_lock_btn_go_p2p": "💬 去私聊操作",
    "repo_lock_btn_force_release": "🔓 强制释放",
    # ── Chat Lock Card ──
    "chat_lock_card_title": "**🔒 群已锁定**",
    "chat_lock_card_desc": "当前群已被锁定，你的消息暂时不会被处理。",
    "chat_lock_locker_name": "锁定者: **{name}**\n",
    "chat_lock_locker_id": "锁定者: `{safe_id}`\n",
    "chat_lock_contact_named": "如需解锁，请联系 {name} 执行 `/unlock` 解锁。\n\n",
    "chat_lock_contact_admin": "如需解锁，请联系 Bot 管理员执行 `/unlock` 解锁。\n\n",
    "chat_lock_contact_ask_group": "管理员列表暂未公开，请在群内询问谁可以解锁。\n\n",
    "chat_lock_allowed_cmds": "💡 锁定期间仍可使用 {cmd_list} 等命令",
    "chat_lock_auto_unlock_hint": "⏰ 锁定将在 **{time}** 后自动解除",
    "chat_lock_locked_at": "锁定时间: **{time}**\n",
    "chat_lock_btn_status": "📊 查看状态",
    "chat_lock_btn_go_p2p": "💬 去私聊操作",
    # ── Lock Success Card ──
    "lock_success_lock_reply": "**🔒 群已锁定**\n\n非 Bot 管理员的指令将不被 Bot 执行。\nBot 管理员可使用 `/unlock` 解锁。\n\n💡 锁定后 {lock_undo_window_display} 内可随时撤销",
    "lock_success_lock_reply_no_undo": "**🔒 已锁定**（由 {locker_name} 锁定）\n\n非 Bot 管理员的指令将不被 Bot 执行。\nBot 管理员可发送 `/unlock` 解锁。",
    "lock_success_lock_reply_no_undo_anonymous": "**🔒 已锁定**\n\n非 Bot 管理员的指令将不被 Bot 执行。\nBot 管理员可发送 `/unlock` 解锁。",
    "lock_success_lock_broadcast": "{by_line}当前群已进入锁定状态，非 Bot 管理员的指令将不被 Bot 执行。",
    "lock_success_lock_idempotent": "**🔒 {message}**\n\n该群当前已锁定，无需重复操作。\nBot 管理员可使用 `/unlock` 解锁。",
    "lock_success_lock_broadcast_by": "（操作者: {name}）",
    "lock_success_lock_broadcast_hint": "\n\n💡 发送 `/help` 或 `/status` 查看详情",
    "lock_success_unlock_reply": "**🔓 群已解锁**\n\n所有成员现在可正常操作。",
    "lock_success_unlock_broadcast": "{by_line}所有成员现在可正常操作。",
    "lock_success_unlock_idempotent": "**🔓 {message}**\n\n该群当前未锁定，无需解锁操作。",
    # ── Lock Undo ──
    "lock_success_lock_undo_btn": "↩️ 撤销",
    "lock_undo_expired": "⏰ 撤销窗口已关闭，如需解锁请发送 /unlock",
    # ── Force Release Confirm Card ──
    "lock_force_release_confirm_title": "**⚠️ 确认强制释放仓库锁？**\n",
    "lock_force_release_confirm_occupied": "仓库 `{repo_name}` 当前正被另一个群会话占用。",
    "lock_force_release_confirm_warn": "强制释放后，对方正在进行的操作可能受到影响。",
    "lock_force_release_confirm_expiry": "\n*此确认在 {minutes} 分钟内有效*",
    "lock_force_release_holder_hint": "💡 持有者已锁定 {duration}",
    "lock_force_release_btn_confirm": "🔓 确认释放",
    "lock_btn_cancel": "❌ 取消",
    # ── Lock Confirm Card ──
    "lock_confirm_title": "**🔒 确认锁定群聊？**\n\n",
    "lock_confirm_desc": "锁定后，非 Bot 管理员的指令将不被 Bot 执行。\n锁定将影响群内所有非 Bot 管理员成员，需确认后生效。\n\n",
    "lock_confirm_admin_only": "*仅 Bot 管理员可操作此按钮*\n",
    "lock_confirm_expiry": "*此确认在 {minutes} 分钟内有效*",
    "lock_confirm_btn": "✅ 确认锁定（仅 Bot 管理员）",
    # ── Chat Lock Manager Messages ──
    "chat_lock_no_admin_config": "群锁定功能需先配置 Bot 管理员列表，请联系 Bot 部署者完成管理员配置",
    "chat_lock_no_admin_config_user": "群锁定功能暂未启用，请联系 Bot 部署者开启此功能",
    "chat_lock_contact_admin_to_lock": "如需锁定群聊，请联系 Bot 管理员",
    "chat_lock_already_locked": "该群已处于锁定状态",
    "chat_lock_locked_success": "群已锁定，非 Bot 管理员将无法操作",
    "chat_lock_contact_named_unlock": "如需解锁群聊，请联系 {name} 执行 /unlock",
    "chat_lock_contact_admin_unlock": "如需解锁群聊，请联系 Bot 管理员执行 /unlock",
    "chat_lock_not_locked": "该群未处于锁定状态",
    "chat_lock_unlocked_success": "群已解锁，所有成员可正常操作",
    # ── System Handler Lock Messages ──
    "lock_cmd_p2p_only": "锁定功能仅在群聊中可用——私聊中你的操作不会与他人冲突，无需加锁",
    "lock_cmd_not_enabled": "群锁定功能暂未启用，请联系 Bot 管理员配置管理员列表",
    "lock_cmd_unknown_sender": "无法识别操作者身份。请尝试：1) 重新发送消息；2) 在私聊中操作；3) 联系 Bot 管理员",
    "lock_cmd_admin_only": "权限不足：仅 Bot 管理员可执行锁定操作。如需操作，请联系 Bot 管理员",
    "lock_cmd_confirm_title": "🔒 群锁定确认",
    "lock_cmd_confirm_expired_title": "🔒 锁定确认已过期",
    "lock_cmd_confirm_expired_msg": "⏰ 确认操作超过 {minutes} 分钟未完成，已自动过期。请重新操作。",
    "lock_btn_retry_lock": "🔒 重新锁定",
    "lock_cmd_cross_chat_reject": "操作失败：该锁定确认仅限在原群中执行",
    "lock_cmd_cancel_lock": "❌ 已取消锁定操作",
    "lock_confirm_deprecated": "此按钮已过期，请重新发送命令",
    "lock_force_release_admin_only": "权限不足：仅 Bot 管理员可强制释放仓库锁。如需操作，请联系 Bot 管理员",
    "lock_repo_mgr_not_init": "仓库锁功能暂不可用，请联系 Bot 管理员",
    "lock_repo_already_released": "该仓库锁已被释放\n\n发送 `/status` 查看当前状态",
    "lock_repo_path_not_found": "未找到对应仓库路径\n\n发送 `/status` 查看当前状态",
    "lock_force_release_confirm_card_title": "⚠️ 强制释放确认",
    "lock_force_release_expired_title": "⚠️ 强制释放确认已过期",
    "lock_btn_retry_force_release": "🔓 再次尝试释放",
    "lock_force_release_success": "**🔓 仓库锁已强制释放**\n\n仓库 `{repo_name}` 的锁已被 Bot 管理员强制释放。",
    "lock_force_release_holder_changed": "⚠️ 该仓库锁状态已变化，请重新查看后再操作",
    "lock_force_release_notify_holder": "**🔓 仓库锁已被释放**\n\n仓库 `{repo_name}` 的锁已被 Bot 管理员从另一个群聊中强制释放。\n如需继续操作，请重新发送命令。",
    "lock_hard_timeout_reclaim_notify": "**🔓 仓库锁已被系统回收**\n\n仓库 `{repo_name}` 的锁因超时（超过系统最大持有时限 {max_hours} 小时）被自动回收。\n如需继续操作，请重新发送命令。",
    "lock_cmd_cancel_force_release": "❌ 已取消强制释放操作",
    "lock_project_not_found_hint": "⚠️ 未找到该项目，项目可能已删除。请发送 /projects 查看项目列表",
    # ── Diagnostics Lock Status ──
    "lock_status_section_header": "**🔒 锁状态**\n\n",
    "lock_status_no_active_lock": "🔓 群/仓库: 未锁定",
    "lock_status_no_lock_explain": "仓库锁在多群同时操作同一仓库时自动生效；群锁可由管理员手动控制",
    "lock_status_chat_locked": "🔒 **群锁定**: 已锁定（仅 Bot 管理员可操作）\n  由 {name} 于 {time} 锁定",
    "lock_status_time_unknown": "未知",
    "lock_status_repo_locked": "🔒 **仓库锁**: `{repo_name}` 已锁定\n  持有者: {holder} | 锁定时长: {duration}{release_hint}",
    "lock_status_holder_self": "当前群（正常状态，你的操作不受影响）",
    "lock_status_holder_other": "另一个群聊",
    "lock_status_release_countdown": " | 预计 {minutes} 分钟后自动释放",
    "lock_status_release_imminent": " | 即将自动释放",
    "lock_status_admin_unlock_hint": "\n  💡 Bot 管理员可使用 `/unlock` 解锁群聊",
    "lock_status_admin_force_release_hint": "\n  💡 Bot 管理员可在仓库锁冲突卡片上点击「🔓 强制释放」按钮，或在私聊中操作机器人",
    "lock_status_nonadmin_repo_hint": "\n  💡 如遇仓库被占用，可联系 Bot 管理员或稍后重试",
    # ── Lock Help Body ──
    "lock_help_admin_group_mgmt": "**管理命令**",
    "lock_help_admin_lock_cmd": "`/lock` · 锁定当前群（直接执行，{lock_undo_window_display}内可撤销）",
    "lock_help_admin_lock_cmd_no_undo": "`/lock` · 锁定当前群（直接执行）",
    "lock_help_admin_unlock_cmd": "`/unlock` · 解锁当前群",
    "lock_help_admin_group_info": "**锁定期间仍可使用的命令**",
    "lock_help_admin_exempt_cmds": "锁定后非 Bot 管理员的指令将不被 Bot 执行，但仍可使用：\n{cmd_list}",
    "lock_help_admin_repo_lock_hint": "当多个群同时操作同一仓库时，系统会自动加锁保护；私聊不受仓库锁限制",
    "lock_help_nonadmin_contact": "如需锁定/解锁群聊，请联系 Bot 管理员操作。",
    "lock_help_nonadmin_repo_hint": "当多个群同时操作同一仓库时，系统会自动加锁保护。如遇仓库被占用提示，可联系 Bot 管理员或稍后重试。",
    "lock_help_nonadmin_exempt_cmds": "锁定后仍可使用以下命令：\n{cmd_list}",
    "lock_help_locked_by_named": "\n🔒 当前群已被 **{name}** 锁定",
    "lock_help_locked_by_admin": "\n🔒 当前群已被 Bot 管理员锁定",
    "lock_help_admin_chat_locked": "\n🔒 当前群: **已锁定**",
    "lock_help_admin_chat_unlocked": "\n🔓 当前群: **未锁定**",
    # ── System Handler Card Titles ──
    "lock_card_title_hint": "ℹ️ 提示",
    "lock_card_title_no_permission": "🔒 权限不足",
    # ── Repo Lock Conflict Fallback ──
    "repo_lock_conflict_fallback": "🔒 仓库被占用，请稍后重试，发送 /status 查看详情。",
    # ── Repo Lock Release Notification ──
    "repo_lock_released_notify": "🔓 仓库 `{repo_name}` 的锁已释放，你可以重新操作了。",
    # ── Retry Empty Command ──
    "retry_empty_command": "⚠️ 无法获取重试命令，请手动重新输入",
    # ── Chat Lock Auto-Unlock Notification ──
    "chat_lock_auto_unlock_notify": "🔓 群锁定已到期自动解除，所有成员现在可正常操作。",
    # ── Retry Handler Messages ──
    "retry_lock_occupied": "🔒 仓库锁被抢占，请稍后重试。发送 `/status` 查看锁状态。",
    # ── Lock Concept Explanation ──
    "lock_dual_concept_explain": "💡 **群锁**（`/lock`）由管理员手动控制，**仓库锁**由系统在操作仓库时自动获取，两者独立。",
    "lock_dual_concept_explain_nonadmin": "💡 **群锁**由管理员手动控制，**仓库锁**由系统在操作仓库时自动获取，两者独立。",
    # ── New keys (architecture UX pass) ──
    "chat_lock_concept_note": "💡 此锁定由管理员手动设置，不影响你在私聊中操作机器人",
    "chat_lock_p2p_guide": "💡 私聊中可直接操作任意仓库，不受群锁和仓库锁限制",
    "lock_status_holder_self_but_chat_locked": "当前群（但群已锁定，非管理员操作仍被拦截）",
    "repo_lock_long_command_hint": "命令较长，无法生成重试按钮，请手动重新发送",
}
