"""UI text constants for card rendering.

Key naming conventions:
- `worktree_*` — canonical keys used by the new CardSession pipeline (reducers/render).
- `system_worktree_*` — keys used by legacy WorktreeHandler message flows.
- `wt_btn_*` — short-form button labels for worktree card actions.
- `system_*` — general system/handler messages (non-card pipeline).
- `<engine>_*` (deep_*, spec_*) — engine-specific card content.
"""

import types

__all__ = ["UI_TEXT"]

# UI Text Constants
UI_TEXT = {
    # Core Card UI
    "log_truncated_warning": "\n> ⚠️ **日志内容过长，已被截断**\n> 🔍 完整日志请查看服务器本地文件\n> (仅显示末尾内容)…\n",
    "claude_mode_title": "🔮 Claude 编程模式",
    "gemini_mode_title": "✨ Gemini 编程模式",
    "coco_mode_title": "编程模式",
    "smart_mode_title": "智能模式",
    "project_dir_label": "📂 项目目录: `{path}`",
    "image_alt_text": "图片 {index}",
    "time_just_now": "刚刚",
    "time_secs_ago": "{seconds} 秒前",
    "time_mins_ago": "{minutes} 分钟前",
    "time_mins_secs_ago": "{minutes} 分钟 {seconds} 秒前",
    "time_hours_ago": "{hours} 小时前",
    "time_hours_mins_ago": "{hours} 小时 {minutes} 分钟前",
    "time_days_ago": "{days} 天前",
    # Deep Engine
    "deep_cmd_help_usage": "📝 请提供需求描述\n\n用法: `/deep <你的需求描述>`\n\n例如: `/deep 帮我写一个 Python 爬虫，爬取豆瓣电影 Top250`",
    "deep_cmd_update_usage": "📝 请提供上下文信息\n\n用法: `/deep_update <上下文描述>`\n\n例如: `/deep_update 数据库改用 PostgreSQL 而不是 SQLite`",
    "deep_cmd_unknown": "❓ 未知的 Deep 命令\n\n可用命令:\n• `/deep <需求>` - 启动 Deep Agent\n• `/deep_update <上下文>` - 注入执行上下文\n• `/deep_status` - 查看当前项目进度\n• `/deep_status --all` - 查看所有项目 Deep Agent 看板\n• `/stop_deep` - 停止当前项目任务\n• `/stop_deep --all` - 停止所有项目任务",
    "deep_task_exists": "⚠️ 当前项目已有 Deep Agent 任务在执行中\n\n发送 `/deep_status` 查看进度\n发送 `/stop_deep` 停止任务",
    "deep_no_task_running": "⚠️ 当前没有正在运行的 Deep Agent 任务\n\n请先使用 `/deep <需求>` 启动任务，或使用 `/deep_status all` 查看所有项目任务",
    "deep_board_empty": "📊 当前没有 Deep Agent 任务\n\n发送 `/deep <需求>` 开始一个复杂任务",
    "deep_status_empty": "📊 当前没有进行中的任务\n\n发送 `/deep <需求>` 开始一个复杂任务",
    "deep_stop_all_success": "⏹ 已发送停止信号：{count} 个 Deep Agent 任务将在当前步骤完成后停止",
    "deep_no_active_tasks": "📊 当前没有正在执行的 Deep Agent 任务",
    # Spec Engine
    "spec_status_empty": "📊 当前没有 Spec 任务\n\n发送 `/spec 你的需求` 开始结构化开发闭环",
    "spec_cmd_guide_usage": "📝 请提供引导信息\n\n用法: `/spec_guide <引导描述>`\n\n例如: `/spec_guide 优先考虑性能优化`",
    "spec_cmd_help_usage": (
        "📋 **Spec 模式：结构化开发闭环**\n\n"
        "用法：`/spec <你的需求描述>`\n"
        "示例：`/spec 实现用户登录注册功能，支持邮箱和手机号`\n\n"
        "**Spec vs Deep**\n"
        "- Spec：按 `Spec→Plan→Task→Build→Review` 产出结构化产物并迭代收敛\n"
        "- Deep：一次性深度拆解并执行一个复杂任务（更偏单次冲刺）\n\n"
        "**最小示例（推荐命令组合）**\n"
        "- Web：`/spec 做一个登录页+登录接口` → `/spec_status` → `/spec_guide 优先补测试与错误提示`\n"
        "- API：`/spec 新增 /v1/users 查询接口` → `/spec_status`\n"
        "- 脚本：`/spec 写一个批量重命名脚本，支持dry-run` → `/spec_status`\n\n"
        "**可用命令**\n"
        "- `/spec <需求>`：启动\n"
        "- `/spec_guide <引导>`：补充约束/偏好（下轮生效）\n"
        "- `/spec_status`：查看进度\n"
        "- `/spec_history`：查看 spec 文件与循环历史\n"
        "- `/spec_metrics`：查看目标达成度与指标变化\n"
        "- `/spec_config`：查看 Spec 长程配置（阈值/保留策略）\n"
        "- `/spec_export`：导出当前 Spec/Plan 报告\n"
        "- `/spec_save`：立即落盘保存状态（用于断点续传）\n"
        "- `/spec_pause`：暂停\n"
        "- `/spec_resume`：恢复\n"
        "- `/spec_recover`：列出或恢复异常中断的任务（需指定 Task ID）\n"
        "- `/stop_spec`：停止\n"
    ),
    # Generic Engine Lifecycle
    "engine_no_active_task": "📊 当前没有正在执行的 {engine_prefix} 任务",
    "engine_multi_resume_conflict": "⚠️ 有多个项目存在可恢复的 {engine_prefix} 任务，请查看状态后切换项目再恢复",
    "engine_no_resumable_task": "当前没有可恢复的 {engine_prefix} 任务",
    "engine_multi_stop_conflict": "⚠️ 有多个项目正在执行 {engine_prefix} 任务，请先切换项目再停止",
    "engine_stop_no_active": "📊 当前没有正在执行的 {engine_prefix} 任务",
    # System Commands
    "system_help_deep_prompt": "💭 启动 Deep Engine\n\n请发送: `/deep <你的需求>`\n\n例如: `/deep 帮我重构 src/feishu 模块`",
    "system_help_project_section": "\n\n📋 **项目管理命令**\n• `/projects` - 查看项目看板\n• `/new 名称 路径` - 创建新项目\n• `/switch 名称` - 切换项目\n• `/status` - 查看所有引擎任务状态（Deep/Spec）\n• `/status <task_id>` - 查看指定任务详情\n• `/diff` - 查看最近两次版本变更（Diff 报告）",
    "system_new_project_usage": "用法: `/new 项目名 [路径]`",
    "system_close_project_usage": "用法: `/close <项目名>`\n例如: `/close myApp`",
    "system_setadmin_bootstrap_success": "✅ 已完成管理员初始化。当前发送者已写入 `.env`，并成为唯一 Bot 管理员。",
    "system_setadmin_update_success": "✅ 已更新 Bot 管理员。当前唯一管理员为 `{admin_id}`。",
    "system_setadmin_denied": "⚠️ Bot 管理员已初始化，只有现有管理员可以修改。",
    "system_setadmin_missing_sender": "无法识别发送者身份，不能设置管理员。",
    "system_setadmin_invalid_target": "管理员 ID 无效。用法：`/setadmin` 或由现有管理员发送 `/setadmin <open_id>`。",
    "system_current_project": "当前项目: **{name}**\n\n{help}{project_help}",
    "system_help_default": "{help}{project_help}",
    "system_mode_smart": "💭 智能模式",
    "system_mode_coco": "🤖 Coco 编程模式",
    "system_mode_claude": "🔮 Claude 编程模式",
    "system_mode_aiden": "🎯 Aiden 编程模式",
    "system_mode_codex": "💻 Codex 编程模式",
    "system_mode_gemini": "✨ Gemini 编程模式",
    "system_mode_ttadk": "🎮 TTADK 多工具模式",
    # Mode name labels (without emoji prefix, used in card title building)
    "mode_name_claude": "Claude 编程模式",
    "mode_name_coco": "编程模式",
    "mode_name_gemini": "Gemini 编程模式",
    "mode_name_smart": "智能模式",
    # Quick action button labels (used in shared.py build_quick_actions)
    "qa_btn_confirm": "✅ 确认",
    "qa_btn_retry": "🔄 重试",
    "qa_btn_cancel": "❌ 取消",
    "qa_btn_continue": "▶️ 继续",
    "qa_btn_next": "⏭️ 下一步",
    "qa_btn_stop": "⏹️ 停止",
    "qa_btn_new_project": "➕ 创建项目",
    "qa_btn_list_projects": "📋 项目列表",
    "system_ttadk_refresh_success": "✅ 已触发 TTADK 模型列表强制刷新",
    "system_ttadk_no_tool": "⚠️ 未指定 TTADK 工具，建议先发送 `/ttadk` 选择工具",
    "system_ttadk_select_tool_error": "❌ 设置 TTADK 工具失败: {tool}",
    "system_ttadk_refresh_error": "❌ 刷新 TTADK 模型列表失败",
    "system_ttadk_get_tools_error": "❌ 获取 TTADK 工具列表失败: {error}",
    "system_ttadk_model_warning": "⚠️ TTADK 模型列表可能不完整/不可信: {warnings}",
    "system_ttadk_switching_model": "🔄 正在切换到模型: {model}…",
    "system_ttadk_set_model_error": "❌ 设置 TTADK 模型失败: {model}",
    "system_ttadk_handler_uninitialized": "❌ TTADK 处理器未初始化",
    "system_ttadk_refresh_label_tool": "工具: `{tool}`",
    "system_ttadk_refresh_label_source": "来源: `{source}`",
    "system_ttadk_refresh_label_warning": "⚠️ 警告: {warnings}",
    "system_ttadk_refresh_label_diag": "诊断: attempts={attempts}",
    "system_ttadk_refresh_footer": "\n最短修复路径：若仍不可用，请确认在项目目录执行过 `ttadk init`，或切换 tool 后重试。",
    "system_switching_to": "🔄 正在切换到 {tool} / {model}…",
    "system_already_in_mode": "💭 当前已经在智能模式中",
    "system_not_set": "未设置",
    "system_default": "默认",
    "system_no_active_project": "⚠️ 当前没有活跃项目，请先创建或切换到一个项目。\n\n发送 `/projects` 查看项目看板",
    "system_auto": "自动",
    "system_on": "开启",
    "system_off": "关闭",
    "system_no_project": "无",
    "system_no_project_display": "无项目",
    "system_unknown_error": "未知错误，请发送 /help 获取帮助",
    "system_unknown_unit": "未知单元",
    "system_unknown_execution_error": "未知执行异常，请重新发送命令重试",
    "system_mode_label": " 模式",
    "system_theme_color_label": "主题色: ",
    "system_history_record_title": " · 历史记录",
    "system_btn_prev_page": "⬅️ 上一页",
    "system_btn_next_page": "➡️ 下一页",
    "system_btn_back_status": "📊 返回状态",
    "system_status_completed": "已完成",
    "system_status_executing": "执行中",
    "system_status_partial_failed": "部分失败",
    "system_status_ready": "就绪",
    "system_status_preparing": "准备中",
    "system_label_current_tool": "🔧 **当前工具**",
    "system_label_current_model": "🤖 **当前模型**",
    "system_status_available": "✅ 可用",
    "system_status_unavailable": "❌ 不可用",
    "system_never_used": "从未使用",
    "system_unknown": "未知",
    "acp_result_text_header": "📝 输出文本",
    "acp_result_plan_header": "📋 计划",
    "acp_result_tools_header": "🛠️ 工具调用",
    "acp_result_tool_results_header": "📦 工具结果(本地记录)",
    "acp_result_files_header": "🗂️ 改动文件",
    "system_ttadk_unavailable": "TTADK 暂不可用",
    "system_ttadk_list_load_error": "暂时无法加载 TTADK 工具列表（{error}）",
    "system_ttadk_model_load_error": "暂时无法加载 TTADK 模型列表（{error}）",
    "system_ttadk_status_banner": "🎮 **TTADK 状态** · 工具: `{tool}` · 模型: `{model}` · 自动执行: `{yolo}`",
    "system_ttadk_info_header": "**🎮 TTADK 当前状态**\n",
    "system_ttadk_info_footer": "\n使用 `/ttadk` 切换工具或模型",
    "system_acp_tool_desc_coco": "字节跳动 AI",
    "system_acp_tool_coco_display": "字节跳动 AI 编程",
    "system_acp_tool_desc_claude": "Anthropic AI",
    "system_acp_tool_desc_aiden": "Aiden CLI",
    "system_acp_tool_aiden_display": "AI 编程助手",
    "system_acp_tool_desc_codex": "OpenAI Codex",
    "system_acp_tool_desc_gemini": "Google Gemini CLI",
    "system_arg_error": "参数错误",
    "system_internal_error": "系统错误",
    "system_slash_parse_missing": "命令解析结果缺失（系统侧），请重新发送该命令重试",
    "system_unknown_slash_command": "未知命令 `{command}`。发送 `/help` 查看可用命令。",
    "system_btw_usage": "请在 `/btw` 后补充要追加给当前编程会话的内容。",
    "system_btw_no_active_session": "当前没有活跃编程会话。请先发送 `/coco`、`/codex` 等进入编程模式。",
    "system_acp_unsupported_tool": "不支持的 ACP 工具: {tool_name}",
    "system_acp_no_available_tools": "未检测到可用 ACP 工具",
    "system_acp_select_tool_prompt": "请选择 ACP 工具",
    "system_acp_select_model_prompt": "请选择 ACP 模型",
    "system_acp_default_model_option": "使用默认模型",
    "system_acp_default_model_desc": "不固定传入模型，使用工具当前默认配置",
    "system_acp_querying_models": "🔍 正在查询 {tool_name} 支持的模型…",
    "system_acp_get_models_failed": "获取 {tool_name} 模型列表失败，请稍后重试",
    "system_acp_model_loading_title": "💭 {tool} 模型选择",
    "system_acp_model_loading_body": "🔍 正在查询 `{tool}` 支持的模型…",
    "system_acp_model_error_title": "⚠️ {tool} 模型加载失败",
    "system_acp_model_error_body": "暂时无法获取 `{tool}` 的模型列表，可以稍后刷新重试。",
    "system_acp_programming_ready_title": "✅ {tool} 编程模式已就绪",
    "system_acp_programming_ready_body": "`{tool}` 已使用 `{model}` 进入编程模式。\n\n现在可以直接在当前会话发送需求。",
    "system_acp_switch_model_btn": "切换模型",
    "system_acp_specify_model_prompt": "请指定模型名称，例如：{example}",
    "system_model_usage_example": "\n• `/model list` — 查看可用模型\n• `/model <name>` — 切换到指定模型",
    "system_worktree_no_selection_error": "请至少选择一个工具-模型组合",
    "system_worktree_created_prompt": "Worktree 已创建，请发送任务目标开始并行执行。",
    "system_worktree_create_failed": "Worktree 创建失败: {error}",
    "system_worktree_cleanup_success": "✅ 所有 Worktree 已清理完成",
    "system_worktree_cleanup_warnings": "⚠️ 清理完成，但以下 Worktree 存在未处理的变更：\n{details}\n\n请手动检查后再次清理。",
    "system_worktree_goal_required": "⚠️ 请先在输入框中填写任务目标",
    "system_worktree_unit_running_error": "⚠️ 存在正在执行的单元，请等待完成后再重试",
    "system_worktree_retry_starting": "🔄 正在重试失败单元…",
    "system_worktree_retry_completed": "重试完成",
    "system_worktree_retry_goal": "重试执行",
    "system_worktree_btn_merge": "🔀 合并到 {base}",
    "system_worktree_btn_cleanup": "🧹 清理 Worktree",
    "system_worktree_merge_title": "🌳 Worktree — 合并结果",
    "system_worktree_merge_header": "**合并详情：**\n",
    "system_worktree_merge_success": "✅ 已成功合并到 {base}",
    "system_worktree_merge_failed": "❌ 合并到 {base} 失败: {error}",
    "system_worktree_cleanup_title": "🌳 Worktree — 清理完成",
    "system_worktree_select_tool_error": "未选择工具",
    "system_worktree_project_not_found": "找不到关联的项目，请先通过 /projects 关联一个项目",
    "system_worktree_no_available_tools": "当前环境没有可用的编程工具。请确认已在项目目录初始化开发工具\n初始化命令: uv sync --group dev（详见 AGENTS.md）",
    "system_worktree_lock_conflict": "🔒 仓库被锁定：{error_detail}\n\n💡 请等待当前操作完成后重试",
    "system_worktree_merging": "🔀 合并中…",
    "system_worktree_no_merge_content": "当前无待合并内容",
    "system_worktree_select_tool_prompt": "请选择要使用的工具：",
    "system_worktree_select_model_prompt": "为 {tool} 选择模型：",
    "system_worktree_selection_finished_banner": "已选择工具: {tool}",
    "spec_review_auto_btn": "Auto：使用主 agent 审查",
    "spec_review_auto_desc": "不额外选择 review 工具，保持当前主任务 agent + 模型的原有流程。",
    "spec_review_select_tool_title": "Spec Review — 选择工具",
    "spec_review_select_model_title": "Spec Review — 选择模型",
    "spec_review_select_message": "请选择后续多角色 review 可使用的工具；也可以直接 Auto 保持原流程。",
    "system_dir_changed_title": "目录已切换",
    "system_error_title": "操作失败",
    "system_ttadk_ai_tool_label": "AI Tool",
    "system_coco_status_title": "**🤖 Coco 状态**\n",
    "system_coco_current_model": "当前模型: `{model}`",
    "system_coco_available_models": "\n**可用模型:**",
    "system_error_prompt_title": "⚠️ 错误提示",
    "system_ref_note_prefix": "🔗 关联：",
    "system_rate_limit_title": "⏸️ 限速等待",
    "system_rate_limit_content": "🔄 API 限速触发，自动等待 {wait_seconds} 秒后恢复…\n\n无需操作，任务将自动继续。",
    "system_shell_success_title": "✅ 命令执行成功",
    "system_shell_failed_title": "❌ 命令执行失败",
    "system_shell_no_output": "✅ 命令执行成功（无输出）",
    "system_shell_return_code": "返回码: `{code}`",
    "system_shell_stderr_label": "⚠️ **错误输出**:",
    "system_ttadk_yolo_on": "⚡ 自动执行：开启（点击关闭）",
    "system_ttadk_yolo_off": "⚡ 自动执行：关闭（点击开启）",
    "system_ttadk_select_tool_prompt": "请选择要使用的 TTADK 工具：",
    "system_ttadk_select_tool_placeholder": "选择工具",
    "system_ttadk_tool_select_title": "🔧 TTADK 工具选择",
    "system_ttadk_select_model_prompt": "请为 {tool} 选择模型：",
    "system_ttadk_select_model_hint": "（若列表为空/不全，可点击下方『🔄 刷新模型列表』强制拉取）",
    "system_ttadk_select_model_placeholder": "选择模型",
    "system_ttadk_refresh_btn": "🔄 刷新模型列表",
    "system_ttadk_model_select_title": "🤖 {tool} 模型选择",
    "system_ttadk_combined_select_prompt": "请选择要使用的 TTADK 工具和模型：",
    "system_ttadk_label_tool": "**🔧 工具**",
    "system_ttadk_label_model": "**🤖 模型** (工具: {tool})",
    "system_ttadk_combined_title": "🔧 TTADK 工具与模型选择",
    "system_ttadk_unavailable_title": "⚠️ TTADK 暂不可用",
    "system_ttadk_soft_failure_msg": "⚠️ {reason}\n\n已为你保留选择，可点击继续或稍后重试。",
    "system_ttadk_btn_continue": "继续进入 TTADK",
    "system_ttadk_btn_reenter": "🔄 重新进入 TTADK",
    "system_acp_tool_select_title": "🧩 ACP 工具选择",
    "system_acp_model_select_title": "💭 {tool} 模型选择",
    "system_menu_title": "📱 快捷菜单",
    "system_menu_header": "**📱 常用指令菜单**",
    "system_menu_btn_new_project": "新项目",
    "system_menu_btn_switch_project": "切项目",
    "system_menu_btn_deep_task": "Deep",
    "system_menu_btn_worktree": "Worktree",
    "system_menu_btn_status": "状态",
    "system_menu_btn_ttadk": "TTADK",
    "system_menu_btn_acp": "工具",
    "system_menu_btn_help": "📖 帮助",
    "system_help_title": "📖 GhostAP 使用帮助 v{version}",
    "system_help_status_header": "**当前状态** · {mode} · 项目: {project}\n<font color='grey'>{cwd}</font>",
    "system_help_quick_entry": "**常用操作**",
    "system_help_section_modes": "🔄 编程模式切换",
    "system_help_section_modes_body": (
        "`/coco` · 进入 Coco 编程模式（字节跳动 AI）\n"
        "`/claude` · 进入 Claude 编程模式（Anthropic AI）\n"
        "`/aiden` · 进入 Aiden 编程模式\n"
        "`/codex` · 进入 Codex 编程模式\n"
        "`/gemini` · 进入 Gemini 编程模式\n"
        "`/ttadk` · 进入 TTADK 多工具编程模式\n"
        "`/exit` · 退出当前编程模式\n"
        "`/coco_info` · `/claude_info` · `/aiden_info` · `/codex_info` · `/ttadk_info` · 查看会话/模型信息"
    ),
    "system_help_section_deep": "💭 Deep Engine · 复杂任务一次交付",
    "system_help_section_deep_body": (
        "`/deep <需求>` · 启动 Deep Engine\n"
        "`/deep_status` · 查看任务进度\n"
        "`/stop_deep` · 停止任务"
    ),
    "system_help_section_spec": "📋 Spec Engine · 结构化开发闭环",
    "system_help_section_spec_body": (
        "`/spec <需求>` · 启动  ·  `/spec_status` · 查看进度\n"
        "`/spec_pause` · 暂停  ·  `/spec_resume` · 继续\n"
        "`/spec_guide <引导>` · 补充约束/偏好\n"
        "`/spec_history` · 历史  ·  `/spec_metrics` · 目标达成度\n"
        "`/spec_config` · 配置  ·  `/spec_save` · 立即保存\n"
        "`/spec_export` · 导出报告  ·  `/spec_recover [任务ID]` · 恢复失败任务\n"
        "`/stop_spec` · 停止"
    ),
    "system_help_section_project": "📂 项目管理",
    "system_help_section_project_body": (
        "`/projects` · 查看所有项目\n"
        "`/new <名称> [路径]` · 创建新项目\n"
        "`/new-chat <名称> [后缀] [路径]` · 创建/绑定项目群\n"
        "`/switch <名称>` · 切换项目  ·  `/close <名称>` · 关闭项目\n"
        "`/status` · 查看所有引擎任务状态\n"
        "`/diff` · 查看最近两次版本变更"
    ),
    "system_help_section_ttadk": "🤖 TTADK 管理",
    "system_help_section_ttadk_body": (
        "`/ttadk_refresh` · 强制刷新模型列表\n"
        "`/ttadk_info` · 查看当前工具和模型"
    ),
    "system_help_section_worktree": "🌳 Worktree · 多工具并行执行",
    "system_help_section_worktree_body": (
        "`/wt` · 进入 Worktree 工具选择流程\n"
        "`/wt <目标>` · 启动 Worktree 并行执行\n"
        "`/worktree <目标>` · 等价别名（同样支持）\n"
        "分隔符支持空格/Tab：例如 `/wt\\t实现登录功能` 或 `/worktree 实现登录功能`\n"
        "流程：选择工具 → 设定目标 → 自动分配 → 并行执行 → 合并结果"
    ),
    "system_help_section_slock": "🎭 Slock · 飞书群内多 Agent 协作",
    "system_help_section_slock_body": (
        "`/slock` · 在当前群激活 Slock  ·  `/slocks` 或 `/slock list` · 查询 Slock 群并跳转\n"
        "`/new-team <名称>` · 新建 `[Slock]` 标识协作群\n"
        "`/new-role <名称> [--tool codex] [--model <模型>]` · 创建 Agent\n"
        "`/new-role <名称> --template coder` · 从模板创建  ·  `--fork <角色>` · 复制角色\n"
        "`/task assign <任务> [角色]` · 分配任务；省略角色时按技能画像自动选择\n"
        "`/task status` · 查看 Kanban 看板  ·  `/role info <名称>` · 查看角色记忆/技能\n"
        "`/team list/status/dissolve <名称>` · 管理团队  ·  `/slock stop` · 停止当前团队"
    ),
    "system_help_tips": (
        "**💡 使用提示**\n"
        "1. 发送 `/menu` 打开完整快捷菜单\n"
        "2. 发送 `/help` 随时查看帮助\n"
        "3. ⏰ 长时间无更新超过 {timeout_display} 才会关闭/回收；运行中的任务会自动顺延，回收前 {warn_display} 会提醒续期\n"
        "<font color='grey'>调整: CARD_SESSION_IDLE_TIMEOUT</font>"
    ),
    "system_tools_list_title": "🛠️ 工具选择",
    "system_tools_list_header": "**🔧 可用工具列表**",
    "system_tools_list_footer": "可用工具: {available}/{total} • 点击按钮进入对应模式 • 灰色按钮表示工具不可用",
    "system_tools_status_title": "📋 工具状态",
    "system_tools_status_header": "**📊 工具状态详情**",
    "system_tools_status_item": "{emoji} **{name}**\n   状态: {status}\n   最后使用: {last_used}{active_info}",
    "system_tools_status_active_session": "\n   🔴 活跃会话: {chat_id}",
    "system_tools_status_btn_enter": "进入 {name}",
    "worktree_goal_label": "**任务目标：** {goal}",
    "worktree_goal_placeholder": "输入任务目标（选完工具后自动执行）",
    "worktree_selected_header": "**已选组合：**\n",
    "worktree_btn_finish": "完成选择",
    "worktree_select_tool_title": "🌳 Worktree — 选择工具",
    "worktree_select_tool_prompt": "**请选择一个工具加入 Worktree 组合：**\n",
    "worktree_select_ttadk_tool_title": "🌳 Worktree — 选择 TTADK 工具",
    "worktree_select_ttadk_tool_prompt": "**请选择一个 TTADK 工具加入 Worktree 组合：**\n",
    "worktree_skip_model_btn": "跳过（使用默认模型）",
    "worktree_select_model_title": "🌳 Worktree — 选择模型",
    "worktree_confirm_header": "**即将启动以下工具-模型组合：**\n",
    "worktree_confirm_banner": "点击 🚀 开始执行 按钮启动任务",
    "worktree_input_placeholder": "输入任务目标，点击确认后开始执行",
    "worktree_btn_confirm": "确认并开始执行",
    "worktree_btn_reselect": "重新选择",
    "worktree_confirm_title": "🌳 Worktree — 确认组合",
    "worktree_progress_header": "**执行进度：**\n",
    "worktree_fail_reason": "> 🔍 **失败原因**：{error}",
    "worktree_ready_banner": "所有单元已就绪，点击 🚀 开始执行 按钮启动任务",
    "worktree_btn_execute": "🚀 开始并行执行",
    "worktree_btn_retry": "🔄 重试失败单元",
    "worktree_progress_title": "🌳 Worktree — {status}",
    "worktree_result_header": "**🔀 工作单元结果**\n\n{message}\n\n",
    "worktree_btn_view_merge": "查看集成项",
    "worktree_result_title": "工作单元结果",
    "worktree_merge_entry_header": "**🔀 待集成项**\n\n目标分支: `{base}`\n\n",
    "worktree_merge_entry_title": "待集成项",
    "worktree_cleanup_header": "**目标分支：** `{base}`\n",
    "worktree_merge_result_header": "**合并结果：**",
    "worktree_merge_item": "{icon} {name} — {detail}",
    "worktree_pending_merge_header": "**待集成项：**",
    "worktree_failed_units_header": "**失败单元：**",
    "worktree_failed_unit_item": "❌ **{name}** · {title} — {error}",
    "worktree_failed_unit_item_no_title": "❌ **{name}** — {error}",
    "worktree_failed_overflow": "…及 {count} 个其他失败单元",
    "worktree_btn_merge_partial": "✅ 先合并已完成",
    "worktree_btn_merge_all": "合并所有分支",
    "worktree_btn_cleanup": "清理 Worktree",
    "worktree_cleanup_card_title": "🌳 Worktree — 集成与清理",
    "system_ttadk_switch_tool_error": "暂时无法切换 TTADK 工具到 {tool}",
    "system_ttadk_switch_model_error": "暂时无法切换 TTADK 模型到 {model}",
    # Project Commands
    "project_create_success": "✅ 项目 **{name}** 创建成功\n\n📁 路径: `{path}`",
    "project_create_error": "❌ 创建项目失败: {error}",
    "project_not_found_title": "未找到项目",
    "project_switch_success": "✅ 已切换到项目: **{name}**\n\n📁 路径: `{path}`",
    "project_switch_error": "❌ 切换项目失败: {error}",
    "project_not_found": "❌ 未找到项目: {name}",
    "project_not_found_hint": "❌ 未找到项目: {name}\n\n发送 `/projects` 查看所有项目",
    "project_close_success": "✅ 项目 **{name}** 已关闭",
    "project_close_error": "❌ 关闭项目失败: {error}",
    "project_dir_info_title": "目录信息",
    "project_dir_info": "📂 **项目目录**: `{root}`\n📁 **工作目录**: `{cwd}`",
    "project_dir_info_cwd": "• 📁 工作目录: `{cwd}`",
    "project_dir_switched": "✅ 已切换到: `{path}`",
    "project_dir_switched_banner": "目录已切换到: {path}",
    "project_dir_switched_detail": "当前工作目录已成功更新为 `{path}`。",
    "project_dir_switch_failed_banner": "切换目录失败: {path}",
    "project_dir_switch_failed_detail": "无法切换到目标目录: `{path}`",
    "project_dir_not_exist": "目录不存在: {path}",
    "project_current_header": "📁 **当前项目: {name}**",
    "project_id_label": "• 项目 ID: `{id}`",
    "project_status_label": "• 状态: {emoji} {status}",
    "project_coco_status": "• Coco 模式: {status}",
    "project_claude_status": "• Claude 模式: {status}",
    "project_last_active_label": "• 最后活跃: {time_ago}",
    "project_coco_session_header": "\n\n🤖 **Coco 会话**",
    "project_claude_session_header": "\n\n🔮 **Claude 会话**",
    "project_session_id_label": "• 会话 ID: `{id}`",
    "project_session_count_label": "• 对话数: {count}",
    "project_similar_header": "\n\n**相似项目：**",
    "project_restore_info": "\n\n📋 已恢复上下文: {count} 条记录",
    "project_restore_last_mode": ", 上次模式: {mode}",
    "project_switched_content": "已切换到项目 **{name}**\n\n📂 项目目录: `{root}`{context_info}",
    "project_board_title": "📋 项目看板",
    "project_board_empty": "当前没有活动项目\n\n发送 `/new 项目名 [路径]` 创建新项目",
    "project_board_active_section": "**🟢 当前活动项目**",
    "project_board_other_section": "**⚪ 其他项目**",
    "project_info_card_title": "当前项目",
    "project_status_card_title": "项目状态",
    "project_switch_title": "🔄 项目已切换",
    "project_btn_open_group": "进入项目群",
    "project_status_group_label": "• 项目群: {name}",
    "project_status_no_group": "• 项目群: 未绑定",
    "diag_current_mode": "**当前模式**: {mode}",
    "diag_no_active_tasks": "暂无正在进行的任务",
    "diag_no_tasks": "暂无任务",
    "diag_project_header": "### {name} {id_info}",
    "diag_task_line": "- {emoji} `{run_id}` {name} ({task_type}){pct}{msg}",
    "diag_unified_status_header": "**引擎任务 ({count})**\n",
    "diag_engine_line": "- {emoji} **{mode}** · {name}{tid} · {info}",
    "diag_status_all_hint": "\n_发送 `/status all` 查看包括已完成的任务_",
    "diag_no_engine_tasks": "当前没有 Deep/Spec 引擎任务\n\n",
    "diag_engine_launch_hints": "启动任务:\n• `/deep <需求>` — 单次深度执行\n• `/spec <需求>` — 结构化开发",
    "diag_task_board_title": "📋 任务看板",
    "diag_no_active_project_tasks": "当前没有活跃项目，无法按项目查看任务。\n\n发送 /projects 查看项目看板",
    "diag_status_iteration": "迭代{iteration}",
    "diag_status_criteria": "标准{criteria}",
    "diag_status_cycle": "循环{cycle}",
    "diag_unified_status_title": "📊 统一状态",
    "diag_task_detail_deep_title": "📊 Deep 任务详情",
    "diag_task_detail_spec_title": "📊 Spec 任务详情",
    "diag_diff_no_active_project": "当前没有活跃项目，无法生成 Diff 报告。\n\n发送 /projects 选择项目",
    "diag_diff_report_title": "🧾 Diff 报告",
    "diag_diff_usage_footer": "用法：/diff（最近两版） • /diff current（到当前） • /diff N • /diff A..B",
    "diag_trace_not_found": "未找到关联信息：{key}",
    "diag_trace_replies_header": "### 📨 回复消息 ({count})",
    "diag_trace_runs_header": "### 🧵 任务 run_id ({count})",
    "diag_trace_usage_footer": "提示：/trace <id> 支持 origin/reply/run_id/request_id",
    "diag_trace_title": "🔎 关联查询",
    "diag_step_parsing": "解析参数",
    "diag_step_generating": "生成报告",
    "diag_step_completed": "完成",
    "diag_engine_deep": "Deep",
    "diag_engine_spec": "Spec",
    "diag_label_origin_id": "**Origin ID**",
    "diag_label_request_id": "**Request ID**",
    "diag_label_project_id": "**Project ID**",
    "diag_project_id_fmt": "(`{id}`)",
    "diag_task_pct_fmt": " {pct:.0f}%",
    "diag_task_msg_fmt": " — {msg}",
    "diag_task_detail_title": "📊 任务详情",
    "diag_task_name_label": "**任务**: {name}",
    "diag_task_type_label": "**类型**: {type}",
    "diag_task_status_label": "**状态**: {emoji} {status}",
    "diag_task_run_id_label": "**run_id**: `{id}`",
    "diag_task_id_label": "**task_id**: `{id}`",
    "diag_task_progress_label": "**进度**: {msg}",
    "diag_task_not_found": "未找到 task_id: `{id}`\n\n发送 `/status` 查看所有任务",
    "diag_diff_title": "## 🧾 Diff 报告",
    "diag_diff_project_label": "**项目**: {name} (`{id}`)",
    "diag_diff_range_label": "**范围**: v{from_v} → v{to_v}",
    "diag_diff_range_current_label": "**范围**: v{from_v} → 当前",
    "diag_diff_start_reason_label": "**起点原因**: {reason}",
    "diag_diff_end_reason_label": "**终点原因**: {reason}",
    "diag_diff_added_entries_label": "**新增条目**: {count}",
    "diag_diff_no_entries": "✅ 本范围内没有新增上下文条目",
    "diag_diff_file_changes_header": "### 📝 文件变更 ({count})",
    "diag_diff_deep_results_header": "### 💭 Deep 结果 ({count})",
    "diag_diff_deep_item": "- `{name}`：已完成 {done}/{total} 个任务",
    "diag_diff_mode_changes_header": "### 🔄 模式切换 ({count})",
    "diag_diff_summaries_header": "### 📌 AI 摘要 ({count})",
    "diag_diff_conversations_header": "### 💬 对话片段 ({count})",
    "diag_diff_others_header": "### 📎 其他 ({count})",
    "diag_diff_truncated": "\n…（内容过长已截断，使用 /shell cat <path> 查看完整输出）",
    "diag_diff_generating_banner": "🧾 正在生成 Diff 报告…",
    "diag_diff_started_banner": "🧾 已开始生成 Diff 报告…",
    "diag_diff_generating_progress": "🧾 {step}中（{pct}%）…",
    "diag_diff_failed": "生成 Diff 报告失败",
    "diag_diff_exception": "Diff 报告生成异常: {error}",
    "diag_diff_no_record": "该项目暂无上下文记录，无法生成 Diff 报告。",
    "diag_diff_no_bookmarks": "该项目尚无版本书签。\n\n提示：版本书签会在模式切换、项目切换、Deep 完成等关键节点自动创建。",
    "diag_diff_no_current": "该项目尚无版本书签，无法计算 `current` diff。",
    "diag_diff_usage_error": "用法错误：`/diff <A>..<B>`，例如 `/diff 3..5`。",
    "diag_diff_usage_hint": "用法：`/diff [last|current|N|A..B]`，例如 `/diff current` 或 `/diff 2..3`。",
    "diag_diff_version_not_found": "找不到版本 v{vnum}，当前共有 {total} 个版本。",
    "project_board_empty_content": "暂无项目\n\n发送 `/new 项目名 路径` 创建新项目",
    "project_board_total_projects": "共 **{total}** 个项目",
    "project_board_current_marker": " (当前)",
    "project_board_claude_info": " | 🔮 Claude 模式中 (消息数: {count})",
    "project_board_coco_info": " | 🤖 Coco 模式中 (消息数: {count})",
    "project_board_busy_info": " | ⏳ {task_type}",
    "project_board_page_info": "第 {page}/{total} 页",
    "project_board_btn_new": "➕ 新建项目",
    "project_board_btn_switch": "切换到此项目",
    "project_board_btn_continue": "继续开发",
    "project_board_btn_detail": "查看详情",
    "project_board_btn_prev": "⬅️ 上一页",
    "project_board_btn_next": "下一页 ➡️",
    "project_board_btn_refresh": "🔄 刷新",
    "project_created_title": "🎉 新项目已创建",
    "project_btn_start_coco": "🤖 开始 Coco",
    "project_btn_start_claude": "🔮 开始 Claude",
    "project_resume_detected": "🔄 检测到未完成的 {mode} 会话",
    "project_resume_session_id": "• 会话 ID: `{id}`",
    "project_resume_query_count": "• 对话数: {count} 条",
    "project_resume_last_query": "• 最后对话: {query}",
    "project_resume_btn_resume": "🔄 恢复会话",
    "project_resume_btn_new": "➕ 新建会话",
    "project_resume_no_session": "没有可恢复的会话",
    "project_notif_suggestion_header": "💡 **建议下一步:**",
    # ── Programming Mode Prompts (centralized) ──
    "mode_enter_msg": "{emoji} 已进入{name}编程模式\n\n现在可以用自然语言描述你的需求\n\n说「退出模式」或发送 `/exit` 退出",
    "mode_enter_no_project_msg": "{emoji} 已进入 {name} 编程模式\n\n现在可以用自然语言描述你的需求\n\n说「退出模式」或发送 `/exit` 退出",
    "mode_already_in_msg": "已经在{name}编程模式中\n\n{info}\n\n说「退出模式」或发送 /exit 退出",
    "mode_exit_msg": "👋 已退出{name}编程模式\n\n会话已保存，下次可以恢复\n\n当前为 💭 智能模式",
    "mode_exit_pending_msg": "👋 已退出{name}编程模式\n\n当前为 💭 智能模式",
    "mode_not_in_msg": "当前不在 {name} 模式中",
    "mode_thinking_msg": "{emoji} {name} 正在思考…",
    "mode_resume_msg": "🔄 已恢复 {name} 会话\n\n• 会话 ID: `{session_id}`\n• 历史对话: {query_count} 条\n\n{hint}",
    "mode_resume_hint_default": "继续之前的对话吧！",
    "mode_resume_hint_ttadk": "当前模式：🎮 TTADK（可点「切换 TTADK 工具」，或发送 `/exit` 退回智能模式）",
    "mode_session_fail_msg": "{name} 会话启动失败，请重新发送 /{cmd} 开始",
    "ttadk_extra_hint": "\n\n可点击「切换 TTADK 工具」重新选择工具链",
    # ── Worktree Engine Card Prompts ──
    "worktree_ready_intercept_hint": "💡 提示：直接发送消息即可作为任务目标开始执行",
    "worktree_start_silent": "🚀 已开始执行: {goal}\n完成后将自动通知，请稍候…",
    "worktree_executing": "⏳ 正在并行执行: {goal}",
    "worktree_still_running": "⏳ 仍在执行中（{elapsed} 分钟），请耐心等待…",
    "worktree_executing_live": "🔄 执行中: {goal}",
    "worktree_auto_executing_banner": "🚀 正在启动并执行任务…",
    # ── Deep Engine Card Prompts ──
    "deep_error_no_detail": "任务异常中断，发送 {engine_cmd} 重试",
    "deep_error_fallback_no_prefix": "任务异常中断，发送 /deep 重试或 /help 查看可用命令",
    "deep_error_expand_hint": '\n> (展开日志查看更多)…',
    "deep_executing_placeholder": "正在执行…",
    "deep_content_expand_hint": '\n> (展开日志查看更多)',
    "deep_folded_lines_hint": "…(已折叠 {count} 行)…\n",
    "deep_ac_expand_hint": '\n> (展开验收标准查看更多)…',
    "deep_status_failed_zh": "失败",
    "deep_status_completed_zh": "完成",
    "deep_status_finished_zh": "结束",
    "deep_status_planning_zh": "规划",
    "deep_status_analyzing_zh": "分析",
    # ── Shell Truncation ──
    "shell_truncated": "\n…(已截断，使用 /shell cat <path> 查看完整输出)…",
    # ── Streaming Card Collapsible / Continuation ──
    "continuation_stale_stub": "▼ 请查看下方最新卡片",
    # ── ws_client Prompts ──
    "ws_session_fail_msg": "⚠️ {name} 会话启动失败，已退回智能模式，请重新发送 /{cmd} 重试",
    "ws_topic_hint_msg": "💡 当前对话已在编程模式中，直接发送需求即可\n\n如需切换工具，请先发送 `/exit` 回到智能模式，再发送 `/codex`、`/coco` 等命令",
    "topic_engine_switch_blocked": "当前话题已绑定 {current} 模式，不能直接切换到 {requested}。\n\n请先停止当前话题任务，或在主对话中新开一个话题启动 {requested}。",
    "topic_engine_exit_msg": "👋 已退出当前话题的 {engine} 模式\n\n这个话题后续消息将回到智能模式。",
    "ws_exit_deferred_msg": "✅ 已收到 /exit，将在当前任务完成后退出（不中断执行）",
    "ws_active_topic_msg": "💡 你有一个活跃的 {name} 编程话题正在进行中\n\n请在话题中回复继续对话\n如需新建编程环境，请先发送对应的编程模式命令（如 /coco）",
    "ws_backpressure_spec": "⚠️ 系统繁忙，当前 Spec cycle 仍会自动重试，请稍候",
    "ws_backpressure_generic": "⚠️ 系统繁忙，请稍后再试",
    "ws_message_timeout": "⏳ 处理消息超时，请稍后重试",
    "ws_message_internal_error": "❌ 处理消息时发生内部错误，请稍后重试",
    "ws_unsupported_msg_type": "⚠️ 目前仅支持文本、图片和富文本消息",
    "ws_image_only_prefix": "请查看并理解以下图片",
    "ws_system_cmd_gate_blocked": "⏳ 系统指令处理中，按钮暂不可用，请稍后重试",
    "ws_card_action_ack": "已收到操作，正在处理…",
    "ws_project_eviction_notify": "该项目「{name}」暂时与当前群断开连接——因为同时使用的群聊数量已满。你可以随时发送 /project 重新连接",
    "ws_fallback_admin_name": "Bot 管理员",
    # Engine error prefixes
    "engine_error_timeout": "超时",
    "engine_error_exception": "异常",
    # ── Retry / Signature ──
    "retry_command_sig_mismatch": "⚠️ 此按钮已失效，请重新发送命令",
    "retry_command_sig_upgrade_expired": "此按钮已过期，请重新发送命令",
    "retry_project_unavailable": "⚠️ 原项目不可用，请重新操作。",
    # ── LRU Eviction Notification ──
    "eviction_notify_title": "📤 项目已自动解绑",
    "eviction_notify_body": "该项目「{name}」暂时与当前群断开连接——因为同时使用的群聊数量已达 {max} 个上限。\n你可以随时发送 /project 重新连接。",
    "eviction_notify_btn_rebind": "🔗 重新绑定",
    # ── Dispatcher: Intent / Multi-task ──
    "intent_unknown_msg": "🤔 无法理解你的意图，请尝试 /help 查看可用命令",
    "project_close_name_required": "❌ 请指定要关闭的项目名称",
    "multi_task_step_failed": "⚠️ 步骤 {step} 执行失败，后续步骤已取消",
    "multi_task_step_success": "✅ 步骤 {step}: {desc}",
    "multi_task_step_error": "❌ 步骤 {step}: {error}",
    "task_desc_unknown": "未知操作",
    # ── Programming Mode Card / Banner ──
    "mode_card_enter_title": "{emoji} {name}编程模式已开启",
    "mode_card_programming_title": "{emoji} {name}编程模式",
    "mode_enter_banner": "{name} 编程模式已开启",
    "mode_exit_banner": "已退出 {name} 编程模式",
    "mode_exit_card_title": "模式已退出",
    "mode_resume_banner": "{name} 会话已恢复",
    "mode_resume_card_title": "{name} 会话已恢复",
    "mode_resume_card_content": "🔄 已恢复 {name} 会话\n\n会话 ID: `{session_id}`\n\n现在可以继续之前的对话了",
    "mode_resume_no_project_msg": "🔄 已恢复 {name} 会话: `{session_id}`",
    "mode_resume_fail_title": "恢复 {name} 会话失败",
    "mode_session_info_title": "{name} 会话信息",
    "mode_model_switched_banner": "已切换 {name} 模型为: {model}",
    "mode_model_switched_title": "{name} 模型已切换",
    "mode_model_switch_context_kept": "对话上下文已保留，可以继续当前任务。",
    "mode_model_switch_restarted": "已重启会话，可以开始新任务。",
    "mode_model_switch_error": "切换 {name} 模型失败: {error}",
    "mode_startup_timeout_title": "启动 {name} 会话超时",
    "mode_startup_fail_title": "启动 {name} 会话失败",
    "mode_ttadk_startup_timeout": "TTADK 会话启动超时",
    "mode_ttadk_unavailable": "TTADK 会话暂不可用",
    "mode_ttadk_degraded_title": "TTADK 暂不可用",
    "mode_ttadk_degraded_msg": "⚠️ TTADK 后端暂不可用。{tool}\n\n原因摘要：{reason}",
    "mode_ttadk_degraded_details_hint": "诊断详情已收起，点击“查看详情”可查看本次失败摘要。",
    "mode_ttadk_available_mode_label": "Coco",
    "mode_ttadk_available_mode_value": "Coco",
    "mode_invalid_project_path": "⚠️ {msg}\n\n请切换到有效目录后重试",
    "mode_project_dir_label": "📂 项目目录: {path}",
    "mode_exec_complete": "✅ 执行完成",
    "mode_exec_timeout_title": "执行超时",
    "mode_exec_exception_title": "执行异常",
    "mode_exec_timeout_msg": "⏳ 执行超时: {error}",
    "mode_exec_exception_msg": "❌ 执行异常: {error}",
    "mode_working_dir_label": "📁 工作目录: `{path}`",
    # --- Worktree render strings ---
    "worktree_render_load_failed": "内容加载异常（{reason}），请重新发送 /wt 命令重试",
    "worktree_tool_selected": "✅",
    "worktree_tool_unselected": "⬜",
    "worktree_render_selected_items": "**已选组合：**",
    "worktree_add_tool_btn": "+ 添加 {name}",
    "worktree_pick_model_btn": "选择 {name}",
    "worktree_selected_block_title": "**已选组合 ({count})**",
    "worktree_remove_item_btn": "✕ 移除",
    "worktree_clear_items_btn": "🗑️ 清空选择",
    "worktree_confirm_selection_btn": "✅ 确认选择",
    "worktree_confirm_selection_disabled_btn": "✅ 确认选择（至少选 1 个）",
    "worktree_back_to_tools_btn": "← 返回工具选择",
    "worktree_model_select_banner": "**🎯 为 {tool} 选择模型**\n点击下方任一模型即可加入组合，点击下方“{back}”可取消本次添加。",
    "worktree_render_goal": "**目标：** {goal}",
    "worktree_render_fail_reason": "> 🔍 失败原因：{error}",
    "worktree_render_branches_to_merge": "**待合并分支** → `{base_branch}`",
    "worktree_render_merge_and_cleanup": "**合并与清理** → `{base_branch}`",
    "worktree_render_merge_results": "**合并结果：**",
    # --- Worktree reducer footer strings ---
    "worktree_footer_select_tools": "📋 请选择工具",
    "worktree_footer_confirm_hint": "点击确认继续",
    "worktree_footer_silent": "🔇 静默执行中，完成后自动通知",
    "worktree_footer_awaiting_confirm": "⏳ 等待确认",
    "worktree_footer_awaiting_goal": "⏳ 等待任务目标",
    "worktree_footer_finishing": "正在收尾… 完成后将自动进入合并阶段",
    "worktree_footer_pending_merge": "📋 待合并",
    "worktree_footer_merge_cleanup": "🔧 合并与清理",
    # --- Worktree button text (extracted from reducer for i18n consistency) ---
    "wt_btn_confirm_selection": "✅ 确认选择",
    "wt_btn_start": "🚀 开始执行",
    "wt_btn_reselect": "🔄 重新选择",
    "wt_btn_cancel": "⏹️ 停止（保留结果）",
    "wt_btn_retry_failed": "🔄 重新执行失败工具",
    "wt_btn_merge_all": "🔀 合并全部",
    "wt_btn_merge": "合并到 {base}",
    "wt_btn_cleanup": "🧹 清理",
    "wt_btn_abandon": "🗑️ 放弃（丢弃结果）",
    "wt_btn_confirm_abandon": "已创建的 worktree 分支将保留，需手动清理。可使用 /wt cleanup 进行清理。",
    "wt_btn_confirm_merge": "所有分支将合并到 {base_branch}，此操作不可自动撤销。",
    "wt_btn_confirm_merge_title": "确认合并",
    "wt_btn_confirm_cleanup": "将删除所有 worktree 分支及其本地分支，此操作不可逆。",
    "wt_btn_confirm_cleanup_title": "确认清理",
    "wt_btn_confirm_retry": "将重新执行失败单元的 shell 操作，请确认工作区状态安全。",
    "wt_btn_confirm_retry_all": "将重新执行所有单元的 shell 操作，请确认工作区状态安全。",
    "wt_hint_select_at_least_one": "请先选择至少一项工具",
    "wt_btn_stop": "⏹️ 停止（保留结果）",
    # --- Card lifecycle strings ---
    "card_lifecycle_thinking": "💭 正在思考…",
    "card_lifecycle_reasoning": "💭 深度思考中…",
    "card_lifecycle_error_fallback": "❌ 执行异常，请重新发送 {engine_cmd} 启动新任务",
    "card_lifecycle_error_fallback_spec": "❌ 执行异常，发送 /spec_recover 可恢复进度，或重新发送 {engine_cmd} 启动新任务",
    "card_lifecycle_retry_failed": "🔄 重新执行失败工具",
    "card_lifecycle_restart": "🔄 重新开始",
    "card_lifecycle_degraded_primary": "继续使用 {mode}",
    "card_lifecycle_degraded_primary_unknown": "重新发送原命令",
    "card_lifecycle_retry_original": "重试原模式",
    "card_lifecycle_continue_degraded_ack": "✅ 已继续使用 {mode}。你可以直接继续发送消息；如需恢复原能力，可点击重试。",
    "card_lifecycle_continue_degraded_unknown_ack": "当前暂未确定可继续模式，请重新发送原命令或查看诊断。",
    "card_lifecycle_show_details": "查看详情",
    "card_lifecycle_details_collapsed": "🔒 详情已收起：点击“查看详情”后将返回已脱敏、截断的诊断信息。",
    "card_lifecycle_retry_original_started": "🔄 已开始重试原模式：{mode}。请继续关注当前会话反馈。",
    "card_lifecycle_retry_original_manual_required": "已收到重试请求，但当前卡片无法安全自动恢复 {mode}。请重新发送原命令、查看诊断，或在卡片存在可继续模式时使用该模式。",
    "card_lifecycle_retry_original_unavailable": "当前降级卡缺少可自动重试的原模式上下文，请重新发送原命令或查看诊断。",
    "card_lifecycle_cancelled_block": "⚠️ 已取消",
    "card_lifecycle_cancelled_status": "已取消",
    "card_lifecycle_paused": "⏸ 已暂停",
    "card_lifecycle_stopping": "🛑 正在停止…",
    "card_lifecycle_resume": "▶️ 恢复执行",
    "card_lifecycle_blocked": "🚫 任务阻塞",
    "card_lifecycle_archived": "📦 已归档",
    "card_lifecycle_archived_hint": "请查看下方最新卡片获取当前进度。",
    "card_archived_navigate_btn": "📍 查看最新卡片",
    "card_archived_scroll_hint": "💡 请在对话底部查看最新卡片",
    "card_lifecycle_mode_title": "{emoji} {mode_name} 编程模式",
    "card_btn_stop": "⏹️ 停止",
    "card_btn_stopping": "正在停止…",
    "card_btn_stop_confirm": "是否停止？已完成的部分不受影响。",
    "card_btn_skip_retry": "跳过重试",
    "card_btn_restart": "🔄 重新开始",
    "card_tool_running": "🔧 执行中: {tool_name}",
    "card_retry_waiting": "⏳ 等待 {delay_sec} 秒后重试（{attempt}/{max_attempts}）",
    "card_retry_executing": "🔄 重试中 ({attempt}/{max_attempts})",
    "card_retry_exhausted": "❌ 重试已耗尽 ({max_attempts}/{max_attempts})，请重新发送命令启动新任务",
    "card_retry_skip": "ℹ️ 无需重试",
    # --- Card session strings ---
    "card_session_recovery_banner": "进度显示曾中断，当前已恢复",
    "card_session_max_failures_banner": "状态更新暂停，任务仍在运行。最后更新于 {timestamp}。请等待自动恢复，或发送 /status 查看",
    "card_session_max_failures_banner_no_ts": "状态更新暂停，任务仍在运行。请等待自动恢复，或发送 /status 查看最新状态",
    "card_session_toast_closed": "{engine_name}任务已结束，发送 {engine_cmd} 启动新任务",
    "card_session_toast_ttl_closed": "{engine_name}已超时关闭，发送 {engine_cmd} 可重新启动",
    "card_session_toast_failed": "{engine_name}任务已失败，请重新发送 {engine_cmd} 重试",
    "card_session_toast_unknown_action": "该按钮已失效，请在对话中重新发送 {engine_cmd} 或 /help 查看可用命令",
    "card_session_toast_factory_error": "操作异常，请在对话中重新输入命令重试",
    "card_session_toast_dispatch_error": "系统暂时繁忙，请稍等片刻后重新发送命令",
    "card_session_toast_action_ack": "操作已提交，正在处理",
    "card_session_toast_dedup": "操作已受理，请勿重复点击",
    "card_session_terminal_retry_failed": "⚠️ 任务已结束（卡片未能刷新最终状态）。如需查看结果，可重新发送 {engine_cmd}",
    # TTL expiry messages — mutually exclusive triggers:
    # All engine-specific messages follow a consistent structure:
    # TTL expired messages — unified two-line structure: status line + action line
    "card_session_ttl_expired": "⏰ 已超时关闭 · 系统回收资源\n发送 {expired_commands} 重新启动",
    "card_session_ttl_expired_spec": "⏰ {engine_name} 已超时关闭 · 进度已保存\n发送 /spec_recover 恢复进度 / {engine_cmd} 重新启动",
    "card_session_ttl_expired_deep": "⏰ {engine_name} 已超时关闭 · 执行结果已保存\n发送 /deep_status 查看状态 / {engine_cmd} 重新启动",
    "card_session_ttl_expired_worktree": "⏰ {engine_name} 已超时关闭 · 执行结果已保存\n发送 /wt_status 查看状态 / {engine_cmd} 重新启动",
    "card_session_ttl_expired_commands": "",  # dynamically generated below from ENGINE_CMD_MAP
    "card_session_ttl_prewarning": "{engine_name} 会话长时间无更新，将在约 {minutes} 分钟后关闭；执行中的任务会自动顺延。点击下方「保持连接」按钮或发送任意消息即可续期",
    "card_session_ttl_force_close_notice": "⏰ {engine_name} 已因空闲超时关闭（系统回收资源）· 发送 {engine_cmd} 重新启动",
    "card_session_terminal_fallback_notice": "⚠️ 任务已结束，但卡片未能及时更新。请发送 {engine_cmd} 开始新任务，无需点击之前卡片中的按钮",
    "card_session_warning_render_fail": "⚠️ 状态更新异常，任务仍在运行，可发送 {engine_cmd} 查看最新状态",
    "card_session_ttl_lock_contention": "⚠️ 系统繁忙，请稍后重试或发送 {engine_cmd} 重新启动",
    "card_session_toast_completed": "任务已完成，无需额外操作",
    "card_session_rejected_throttled": "当前使用人数较多，将在 {delay} 秒后自动重试（第 {attempt} 次，最多 {max} 次）",
    "card_footer_last_updated": "最后更新于 {timestamp}",
    "ttl_keep_alive_btn": "保持连接（剩余约 {minutes} 分钟）",
    "ttl_keep_alive_toast": "已续期，会话将继续保持活跃",
    "card_btn_disabled_tips": "该按钮当前不可用",
    "card_btn_show_status": "📋 查看状态",
    "card_btn_mode_full": "📋 切换完整模式",
    "card_btn_mode_compact": "📄 切换精简模式",
    "card_btn_force_stop": "⛔ 强制停止",
    "card_btn_confirm_dialog_title": "确认",
    "card_btn_confirm_stop_title": "确定停止当前任务？",  # DEPRECATED: use _normal or _danger variant
    "card_btn_confirm_stop_title_normal": "确定停止当前任务？",
    "card_btn_confirm_stop_title_danger": "强制停止当前任务",
    "card_btn_confirm_stop_body": "进行中的执行将中断，已完成的部分不受影响",
    "card_btn_confirm_stop_body_normal": "正在进行的步骤将中断，已保存的产物不受影响",
    "card_btn_confirm_stop_danger_body": "⚠️ 强制停止将中断一切进度（普通停止仅中断当前步骤，已完成部分保留）。\n已提交的代码不受影响，发送 {engine_cmd} 可重新开始。",
    "card_btn_confirm_retry_title": "重新执行任务",
    "card_btn_confirm_retry_body": "确认重新执行？上次执行的结果将被替换",
    "card_btn_confirm_execute_title": "开始执行任务",
    "card_btn_confirm_merge_title": "合并分支",
    "card_btn_confirm_cleanup_title": "清理 Worktree",
    "card_btn_confirm_approve_title": "授权执行",
    "card_btn_confirm_reject_title": "拒绝请求",
    "card_btn_confirm_default_title": "确认操作",
    "card_btn_confirm_cancel_title": "取消当前操作",
    "card_btn_confirm_cancel_body": "操作将被中止，已创建的资源可能需要手动清理",
    "btn_confirm_template": "确认「{text}」？",
    "card_stop_escalation_hint": "任务未响应停止信号时将出现强制停止选项",
    "card_stop_escalation_countdown": "约半分钟后可强制停止",
    "card_session_toast_cancelled": "{engine_name}任务已取消，发送 {engine_cmd} 重新启动",
    "card_session_rejected_notice": "⚠️ 当前系统繁忙，请稍等片刻后重试，或重新发送 {engine_cmd}",
    "card_session_rejected_shutdown": "⚠️ 系统维护中，请稍后再试",
    "card_session_rejected_banner": "系统繁忙，请稍后重试",
    "card_session_toast_btn_completed": "{engine_name}任务已完成，按钮不再可用。发送 {engine_cmd} 可开始新任务",
    "card_session_toast_btn_ttl_expired": "{engine_name}已超时关闭，按钮不再可用。重新发送 {engine_cmd} 可开始新任务",
    # --- Footer ---
    "card_footer_duration_fmt": "耗时 {duration}",
    "card_footer_elapsed_total_fmt": "已执行 {duration}",
    "card_footer_system_notice": "（系统提示）",
    "card_footer_idle_timeout_hint": "长时间无更新超过 {timeout_display} 后才会回收；执行中任务会自动顺延",
    "card_footer_frozen_continuation": "本卡已停止更新 · 续接 #{next_seq} ↓",
    "duration_sub_second": "< 1 秒",
    "duration_secs": "{seconds} 秒",
    "duration_mins_secs": "{minutes} 分钟 {seconds} 秒",
    "duration_hours_mins_secs": "{hours} 小时 {minutes} 分钟 {seconds} 秒",
    # --- Progress semantic label ---
    "card_progress_criteria_label": "验收",
    "card_progress_tool_label": "工具进度",
    "card_progress_worktree_label": "执行",
    # --- Criteria panel ---
    "criteria_panel_header": "📋 **验收标准**",
    "criteria_panel_header_with_count": "📋 **验收标准** ({satisfied}/{total})",
    # --- Card session retry ---
    "card_session_retry_pending_banner": "更新中，请稍候",
    # --- Lock undo window ---
    "lock_undo_window_duration": "{minutes} 分钟",
    "lock_undo_window_closed": "撤销窗口已关闭",
    # --- Worktree stepper ---
    "worktree_step_tool_select": "选择工具",
    "worktree_step_model_select": "选择模型",
    "worktree_step_confirm": "确认选择",
    "worktree_step_awaiting_goal": "等待目标",
    "worktree_step_units": "执行任务",
    "worktree_step_merge": "集成与清理",
    "worktree_step_cleanup": "清理与收尾",
    # --- Worktree stepper hints (grey notation at panel top) ---
    "worktree_step_tool_select_hint": "可重复选择多个工具组成并行组合，每点一项即加入下方已选区",
    "worktree_step_model_select_hint": "为刚选中的工具挑选模型，点击模型即可加入组合；可点击下方“返回工具选择”取消",
    "worktree_step_confirm_hint": "确认已选工具和任务目标，点击开始后将并行启动执行",
    "worktree_step_awaiting_goal_hint": "已确认工具组合；请在当前话题直接发送任务目标，收到后自动开始执行",
    "worktree_step_units_hint": "执行中，完成后可查看各分支结果并合并",
    "worktree_step_merge_hint": "执行完成，可将各分支变更合并到主分支",
    "worktree_step_cleanup_hint": "合并完成，可清理 worktree 分支并收尾",
    # --- Worktree merge status (Chinese) ---
    "worktree_merge_status_ready": "就绪",
    "worktree_merge_status_conflict": "冲突",
    "worktree_merge_status_merged": "已合并",
    # --- Worktree render hardcoded text extraction ---
    "worktree_data_empty": "数据为空",
    "worktree_execution_unit": "执行单元",
    # --- Worktree header titles (no emoji, consistent prefix) ---
    "worktree_header_tool_select": "Worktree · 工具选择",
    "worktree_header_confirm": "Worktree · 确认配置",
    "worktree_header_execute": "Worktree · 并行执行",
    "worktree_header_integrate": "Worktree · 集成清理",
    "worktree_header_completed": "Worktree · 执行完成",
    "worktree_completed_subtitle": "✅ 全部完成",
    # --- Worktree buttons ---
    "wt_btn_retry_all": "🔄 重新执行",
    "worktree_no_change_subtitle": "无可合并变更",
    "worktree_completed_no_change": "执行完成，未产生代码变更",
    # --- Content error ---
    "card_content_load_error": "部分内容暂时无法渲染，请稍后重试或联系管理员。",
    "card_content_load_error_running": "部分内容暂时无法渲染，任务仍在运行中，后续更新将自动恢复。",
    # --- New keys for review feedback ---
    "card_lifecycle_blocked_reason_fmt": "🚫 **任务阻塞** — {reason}",
    "worktree_step_label_fmt": "步骤 {num}/{total} · {title}",
    "card_completed_cta_fmt": "发送 /{engine_cmd} 启动新任务",
    "card_project_failed": "项目未能成功完成",
    # --- Tool panel labels ---
    "tool_label_command": "**命令**",
    "tool_label_result": "**结果**",
    "tool_label_input": "**输入**",
    "tool_label_output": "**输出**",
    # --- Phase display names ---
    "phase_planning": "规划中",
    "phase_coding": "编码中",
    "phase_review": "审查中",
    "phase_spec_review": "规格审查中",
    "phase_spec": "规格定义中",
    "phase_plan": "方案规划中",
    "phase_task": "任务分解中",
    "phase_build": "执行构建中",
    "spec_review_phase_done": "多角色审查完成",
    "phase_testing": "测试中",
    "phase_building": "构建中",
    "phase_deploying": "部署中",
    "phase_analyzing": "分析中",
    "phase_refactoring": "重构中",
    "phase_debugging": "调试中",
    "phase_default": "进行中",
    # --- Reasoning panel ---
    "reasoning_panel_thinking": "💭 **深度思考中…**",
    "reasoning_panel_done": "💭 **思考完成** · {char_count}字",
    # --- Truncation (extracted from payload_truncator.py) ---
    "truncation_suffix": "…(已截断)",
    "truncation_warning_with_cmd": "⚠️ 内容过长已自动截断。请发送 {cmd_hint} 查看完整内容",
    "truncation_warning_generic": "⚠️ 内容过长已自动截断。可重新发送命令获取最新状态",
    "truncation_fallback_prefix": "内容过长无法完整展示。",
    "truncation_fallback_suffix": "\n\n…(内容过长已截断)",
    "truncation_card_header": "⚠️ 卡片过大",
    # --- Session inline text (extracted from session.py) ---
    "card_session_paused_notice": "状态更新暂停，任务仍在运行",
    "card_session_fallback_cmd": "/help 查看可用命令",
    "card_session_fallback_engine_name": "任务",
    # --- Hook failure notice (extracted from hooks.py) ---
    "hook_persistence_failed_notice": "⚠️ 执行结果保存失败，您可重新运行 {engine_cmd} 查看最新结果",
    # --- Session rotation truncation ---
    "card_session_rotation_truncated": "⚠️ 这是最后一张卡片，内容将精简显示。后续输出合并于此，超出部分可能被截断。{cmd_hint}",
    # --- Task orchestrator ---
    "orch_plan_archived": "✅ 规划完成 — 共 {task_count} 个任务\n{task_list}",
    "orch_continuation_link": "↓ 第 {seq} 篇 · [{link_text} →](lark://message/{msg_id})",
    "orch_continuation_link_fallback": "↓ 第 {seq} 篇 · 请查看下方最新卡片",
    "orch_continuation_hint": "↩ 第 {page} 篇 · 承接前篇",
    "orch_task_continuation_nav": "\n\n---\n↓ 任务「{task_name}」第 {page} 篇 · [{link_text} →](lark://message/{msg_id})",
    "orch_task_continuation_nav_fallback": "\n\n---\n↓ 任务「{task_name}」第 {page} 篇 · 请查看下方最新卡片",
    "orch_fallback_warning": "⚠️ 任务已合并展示（可能由网络波动引起，不影响执行结果；如持续出现请联系管理员）",
    "orch_flood_merged": "📎 任务「{task_name}」已合并展示于此",
    "orch_archived_navigate_fallback": "↓ 内容已续至下方卡片，请查看下方最新卡片",
    "orch_plan_transition_hint": "以下每个任务将在独立卡片中展示 · [查看首个任务 →](lark://message/{first_task_msg_id})",
    "orch_plan_transition_hint_no_link": "以下每个任务将在独立卡片中展示 ↓",
    "orch_plan_transition_hint_overflow": "以下 {independent_count} 个任务将在独立卡片中展示，其余 {merged_count} 个合并至最后一张 ↓",
    "orch_back_link": "↑ [前篇](lark://message/{msg_id})",
    "orch_back_link_with_task": "↑ [「{task_name}」前篇](lark://message/{msg_id})",
    "orch_nav_link_text": "查看最新卡片",
    "orch_overflow_separator": "---\n📎 {status_emoji} **{task_name}**\n",
    "orch_overflow_separator_first": "---\n📌 以下任务合并展示\n\n---\n📎 {status_emoji} **{task_name}**\n",
    "orch_overflow_collapsed": "---\n📌 …及 {count} 项更多任务合并展示\n",
    "orch_rotation_failed_notice": "⚠️ 内容过长无法创建新卡片，后续内容将继续在本卡片追加",
    "orch_final_summary_task_name": "任务总结",
    # --- Task status prefixes ---
    "orch_task_status_pending": "⏳",
    "orch_task_status_running": "🔄",
    "orch_task_status_done": "✅",
    "orch_task_status_failed": "❌",
    # --- Renderer inline text ---
    "deep_exec_start": "🚀 ACP Deep 执行开始\n\n📂 **{project_name}**\n🔗 路径: `{root_path}`",
    "deep_phase_executing": "🔄 执行中",
    "deep_phase_planning": "🧠 分析/规划中",
    "deep_spec_style_subtitle_analyzing": "Deep · 分析",
    "deep_spec_style_subtitle_build": "Deep · 执行",
    "deep_spec_style_analyzing_done": "分析与任务拆解已完成。",
    "deep_spec_style_build_done": "执行阶段已完成。",
    "deep_exec_completed": "✅ 执行完成 · 工具调用: {tool_calls_count}",
    "deep_exec_incomplete": "⚠️ 执行未完成（已完成 {completed}/{total} 步）\n💡 重试: /deep 继续执行",
    "deep_progress_executing": "执行中",
    "deep_progress_done": "已完成",
    "spec_cycle_label": "第 {cycle_num} 轮",
    "spec_build_progress": "🔨 {tool_count} 次工具调用",
    "spec_build_progress_files": " · {file_count} 文件",
    "spec_build_done": "🔨 **构建完成**  {summary}",
    "spec_build_done_plain": "🔨 **构建完成**",
}

# Merge spec-engine UI text from the shared utils layer (avoids card→engine reverse dep)
from ..utils.ui_text import SPEC_UI_TEXT  # noqa: E402

_spec_overlap = UI_TEXT.keys() & SPEC_UI_TEXT.keys()
if _spec_overlap:
    raise RuntimeError(f"UI_TEXT key conflict with SPEC_UI_TEXT: {_spec_overlap}")
UI_TEXT.update(SPEC_UI_TEXT)

# Merge lock-related UI text from dedicated module
from .styles_lock import LOCK_UI_TEXT  # noqa: E402

_lock_overlap = UI_TEXT.keys() & LOCK_UI_TEXT.keys()
if _lock_overlap:
    raise RuntimeError(f"UI_TEXT key conflict with LOCK_UI_TEXT: {_lock_overlap}")
UI_TEXT.update(LOCK_UI_TEXT)

# Dynamically generate TTL expired commands list from engine metadata (single source of truth)
from .engine_meta import ENGINE_CMD_MAP  # noqa: E402

_cmds = list(ENGINE_CMD_MAP.values())
UI_TEXT["card_session_ttl_expired_commands"] = (
    "、".join(_cmds[:-1]) + " 或 " + _cmds[-1] if len(_cmds) > 1 else _cmds[0]
)

# Keep mutable reference for testing (mock.patch.dict targets this)
_MUTABLE_UI_TEXT = UI_TEXT

# Freeze UI_TEXT as read-only to prevent accidental runtime mutation
UI_TEXT = types.MappingProxyType(UI_TEXT)  # type: ignore[assignment]
