import logging
from typing import Any

logger = logging.getLogger(__name__)

# Dispatch table: _method_name -> (registry_key, handler_method_name)
FORWARDING_MAP: dict[str, tuple[str, str]] = {
    # --- shared base handler helpers (delegate via coco) ---
    "_add_reaction": ("coco", "add_reaction"),
    "_get_working_dir": ("coco", "get_working_dir"),
    "_set_working_dir": ("coco", "set_working_dir"),
    "_ensure_request_id": ("coco", "ensure_request_id"),
    "_format_ref_note": ("coco", "format_ref_note"),
    "_register_message_project": ("coco", "register_message_project"),
    "_reply_message": ("coco", "reply_message"),
    "_reply_message_with_id": ("coco", "reply_message_with_id"),
    "send_message": ("coco", "send_message"),
    "_get_engine_name": ("coco", "get_engine_name"),
    "_record_mode_transition": ("coco", "record_mode_transition"),
    "_inject_bridge_context": ("coco", "inject_bridge_context"),
    # --- Coco mode ---
    "_enter_coco_mode": ("coco", "enter_mode"),
    "_exit_coco_mode": ("coco", "exit_mode"),
    "_handle_coco_message": ("coco", "handle_message"),
    "_handle_coco_response": ("coco", "handle_response"),
    "_show_coco_info": ("coco", "show_info"),
    "_handle_card_enter_coco": ("coco", "handle_card_enter"),
    "_handle_card_exit_coco": ("coco", "handle_card_exit"),
    "_handle_card_resume_coco": ("coco", "handle_card_resume"),
    "_handle_card_new_coco": ("coco", "handle_card_new"),
    # --- Claude mode ---
    "_enter_claude_mode": ("claude", "enter_mode"),
    "_exit_claude_mode": ("claude", "exit_mode"),
    "_handle_claude_message": ("claude", "handle_message"),
    "_handle_claude_response": ("claude", "handle_response"),
    "_show_claude_info": ("claude", "show_info"),
    "_handle_card_enter_claude": ("claude", "handle_card_enter"),
    "_handle_card_exit_claude": ("claude", "handle_card_exit"),
    "_handle_card_resume_claude": ("claude", "handle_card_resume"),
    "_handle_card_new_claude": ("claude", "handle_card_new"),
    # --- Aiden mode ---
    "_enter_aiden_mode": ("aiden", "enter_mode"),
    "_exit_aiden_mode": ("aiden", "exit_mode"),
    "_handle_aiden_message": ("aiden", "handle_message"),
    "_handle_aiden_response": ("aiden", "handle_response"),
    "_show_aiden_info": ("aiden", "show_info"),
    "_handle_card_enter_aiden": ("aiden", "handle_card_enter"),
    "_handle_card_exit_aiden": ("aiden", "handle_card_exit"),
    "_handle_card_resume_aiden": ("aiden", "handle_card_resume"),
    "_handle_card_new_aiden": ("aiden", "handle_card_new"),
    # --- Gemini mode ---
    "_enter_gemini_mode": ("gemini", "enter_mode"),
    "_exit_gemini_mode": ("gemini", "exit_mode"),
    "_handle_gemini_message": ("gemini", "handle_message"),
    "_handle_gemini_response": ("gemini", "handle_response"),
    "_show_gemini_info": ("gemini", "show_info"),
    "_handle_card_enter_gemini": ("gemini", "handle_card_enter"),
    "_handle_card_exit_gemini": ("gemini", "handle_card_exit"),
    "_handle_card_resume_gemini": ("gemini", "handle_card_resume"),
    "_handle_card_new_gemini": ("gemini", "handle_card_new"),
    # --- Codex mode ---
    "_enter_codex_mode": ("codex", "enter_mode"),
    "_exit_codex_mode": ("codex", "exit_mode"),
    "_handle_codex_message": ("codex", "handle_message"),
    "_handle_codex_response": ("codex", "handle_response"),
    "_show_codex_info": ("codex", "show_info"),
    "_handle_card_enter_codex": ("codex", "handle_card_enter"),
    "_handle_card_exit_codex": ("codex", "handle_card_exit"),
    "_handle_card_resume_codex": ("codex", "handle_card_resume"),
    "_handle_card_new_codex": ("codex", "handle_card_new"),
    # --- TTADK mode ---
    "_enter_ttadk_mode": ("ttadk", "enter_mode"),
    "_exit_ttadk_mode": ("ttadk", "exit_mode"),
    "_handle_ttadk_message": ("ttadk", "handle_message"),
    "_handle_ttadk_response": ("ttadk", "handle_response"),
    "_show_ttadk_info": ("ttadk", "show_info"),
    "_handle_card_enter_ttadk": ("ttadk", "handle_card_enter"),
    "_handle_card_exit_ttadk": ("ttadk", "handle_card_exit"),
    "_handle_card_resume_ttadk": ("ttadk", "handle_card_resume"),
    "_handle_card_new_ttadk": ("ttadk", "handle_card_new"),
    "_handle_ttadk_command": ("system", "handle_ttadk_command"),
    "_handle_worktree_command": ("worktree", "handle_worktree_command"),
    "_handle_worktree_execute": ("worktree", "handle_worktree_execute"),
    "_handle_finish_worktree_selection": ("worktree", "handle_finish_worktree_selection"),
    "_handle_worktree_select_tool": ("worktree", "handle_worktree_select_tool"),
    "_handle_worktree_select_model": ("worktree", "handle_worktree_select_model"),
    "_handle_worktree_confirm_start": ("worktree", "handle_worktree_confirm_start"),
    "_handle_worktree_execute_action": ("worktree", "handle_worktree_execute_action"),
    "_handle_worktree_merge": ("worktree", "handle_worktree_merge"),
    "_handle_worktree_cleanup": ("worktree", "handle_worktree_cleanup"),
    "_handle_worktree_retry_failed": ("worktree", "handle_worktree_retry_failed"),
    "_handle_select_ttadk_tool": ("system", "handle_select_ttadk_tool"),
    "_handle_select_ttadk_model": ("system", "handle_select_ttadk_model"),
    "_handle_refresh_ttadk_models": ("system", "handle_refresh_ttadk_models"),
    "_handle_toggle_ttadk_yolo": ("system", "handle_toggle_ttadk_yolo"),
    "_handle_select_ttadk_combined": ("system", "handle_select_ttadk_combined"),
    "_handle_acp_command": ("system", "handle_acp_command"),
    "_handle_select_acp_tool": ("system", "handle_select_acp_tool"),
    "_handle_select_acp_model": ("system", "handle_select_acp_model"),
    "_handle_refresh_acp_models": ("system", "handle_refresh_acp_models"),
    "_handle_help_category": ("system", "handle_help_category"),
    "_handle_deep_prompt": ("system", "handle_deep_prompt"),
    # --- Deep Engine ---
    "_handle_deep_command": ("deep", "handle_deep_command"),
    "_start_deep_engine": ("deep", "start_deep_engine"),
    "_create_deep_callbacks": ("deep", "_create_deep_callbacks"),
    "_show_deep_status": ("deep", "show_deep_status"),
    "_show_deep_board": ("deep", "show_deep_board"),
    "_pause_deep_engine": ("deep", "pause_deep_engine"),
    "_resume_deep_engine": ("deep", "resume_deep_engine"),
    "_stop_deep_engine": ("deep", "stop_deep_engine"),
    "_stop_all_deep_engines": ("deep", "stop_all_deep_engines"),
    "_update_deep_context": ("deep", "update_deep_context"),
    "_toggle_deep_log": ("deep", "_toggle_log"),
    "_switch_deep_card_mode": ("deep", "_switch_card_mode"),
    # --- Loop Engine ---
    "_handle_loop_command": ("loop", "handle_loop_command"),
    "_start_loop_engine": ("loop", "start_loop_engine"),
    "_show_loop_status": ("loop", "show_loop_status"),
    "_pause_loop_engine": ("loop", "pause_loop_engine"),
    "_resume_loop_engine": ("loop", "resume_loop_engine"),
    "_stop_loop_engine": ("loop", "stop_loop_engine"),
    "_update_loop_guidance": ("loop", "update_loop_guidance"),
    "_toggle_loop_log": ("loop", "_toggle_log"),
    "_switch_loop_card_mode": ("loop", "_switch_card_mode"),
    # --- Spec Engine ---
    "_handle_spec_command": ("spec", "handle_spec_command"),
    "_start_spec_engine": ("spec", "start_spec_engine"),
    "_show_spec_status": ("spec", "show_spec_status"),
    "_pause_spec_engine": ("spec", "pause_spec_engine"),
    "_resume_spec_engine": ("spec", "resume_spec_engine"),
    "_stop_spec_engine": ("spec", "stop_spec_engine"),
    "_update_spec_guidance": ("spec", "update_spec_guidance"),
    "_toggle_spec_log": ("spec", "_toggle_log"),
    "_switch_spec_card_mode": ("spec", "_switch_card_mode"),
    "_toggle_spec_ac": ("spec", "_toggle_ac"),
    # --- Project ---
    "_create_project": ("project", "create_project"),
    "_show_project_board": ("project", "show_project_board"),
    "_show_current_project": ("project", "show_current_project"),
    "_show_project_status": ("project", "show_project_status"),
    "_preserve_project_context": ("project", "preserve_project_context"),
    "_restore_project_context": ("project", "restore_project_context"),
    "_close_project": ("project", "close_project"),
    # --- System ---
    "_show_help": ("system", "show_help"),
    "_show_full_help": ("system", "show_full_help"),
    "_exit_current_mode": ("system", "exit_current_mode"),
    "_submit_shell_command": ("system", "submit_shell_command"),
    "_change_directory": ("system", "change_directory"),
    "_handle_intercepted_command": ("system", "handle_intercepted_command"),
    "_handle_force_release_repo_lock": ("system", "handle_force_release_repo_lock"),
    "_handle_confirm_lock": ("system", "handle_confirm_lock"),
    "_handle_cancel_lock": ("system", "handle_cancel_lock"),
    "_handle_confirm_force_release": ("system", "handle_confirm_force_release"),
    "_handle_cancel_force_release": ("system", "handle_cancel_force_release"),
    # --- Diagnostics ---
    "_show_task_board": ("diagnostics", "show_task_board"),
    "_show_context_diff": ("diagnostics", "show_context_diff"),
    "_build_context_diff_report": ("diagnostics", "_build_context_diff_report"),
    "_submit_diff_report": ("diagnostics", "_submit_diff_report"),
    "_show_message_trace": ("diagnostics", "show_message_trace"),
}

def bind_forwarding_methods(client: Any, handler_ctx: Any) -> None:
    """
    Bind forwarding methods directly on the client instance.
    """
    for attr_name, (handler_key, method_name) in FORWARDING_MAP.items():
        handler = handler_ctx.handlers.get(handler_key)
        if handler:
            setattr(client, attr_name, getattr(handler, method_name))
